import type { TheoryItem } from '../study/generators/theory'

// COLREG theory questions. The first option is the correct one; the app shuffles them.
// Every question names its rule so it can be checked against the text.

export const COLREGS_THEORY: (TheoryItem & { id: string })[] = [
  {
    id: 'R5',
    q: 'Rule 5 requires every vessel to keep a proper look-out by:',
    options: [
      'Sight and hearing, and all available means appropriate in the circumstances',
      'Radar only, when the visibility is restricted',
      'Sight only, from the bridge',
      'Sight and hearing, but only at night',
    ],
    why: 'Rule 5: a proper look-out by sight and hearing as well as by all available means appropriate in the prevailing circumstances and conditions.',
    source: 'Rule 5',
  },
  {
    id: 'R6',
    q: 'According to Rule 6, a safe speed is a speed at which you can:',
    options: [
      'Take proper and effective action to avoid collision and be stopped within a distance appropriate to the circumstances',
      'Always stop within your own length',
      'Keep to the speed limit shown on the chart',
      'Maintain steerage way and nothing more',
    ],
    why: 'Rule 6: every vessel shall at all times proceed at a safe speed so that she can take proper and effective action to avoid collision and be stopped within a distance appropriate to the prevailing circumstances and conditions.',
    source: 'Rule 6',
  },
  {
    id: 'R7d',
    q: 'Which observation means that risk of collision shall be deemed to exist?',
    options: [
      'The compass bearing of an approaching vessel does not appreciably change',
      'The relative bearing of the other vessel changes quickly',
      'You can see her sternlight',
      'She is more than 6 nautical miles away',
    ],
    why: 'Rule 7(d)(i): such risk shall be deemed to exist if the compass bearing of an approaching vessel does not appreciably change. It may sometimes exist even when an appreciable bearing change is evident, especially with a very large vessel, a tow or at close range.',
    source: 'Rule 7(d)',
  },
  {
    id: 'R7c',
    q: 'What does Rule 7 warn you against?',
    options: [
      'Making assumptions on the basis of scanty information, especially scanty radar information',
      'Using radar in clear weather',
      'Taking bearings with a gyro compass',
      'Calling other vessels on VHF',
    ],
    why: 'Rule 7(c): assumptions shall not be made on the basis of scanty information, especially scanty radar information.',
    source: 'Rule 7(c)',
  },
  {
    id: 'R8',
    q: 'What does Rule 8 say about alterations of course and speed to avoid collision?',
    options: [
      'They should be large enough to be readily apparent to another vessel; avoid a succession of small alterations',
      'They should be small, so that the other vessel is not confused',
      'Only alterations of course are allowed, never of speed',
      'They should be made as late as possible',
    ],
    why: 'Rule 8(b): any alteration of course and/or speed should, if the circumstances admit, be large enough to be readily apparent to another vessel observing visually or by radar; a succession of small alterations should be avoided.',
    source: 'Rule 8(b)',
  },
  {
    id: 'R9',
    q: 'In a narrow channel, a vessel of less than 20 m or a sailing vessel shall:',
    options: [
      'Not impede the passage of a vessel which can safely navigate only within the channel',
      'Always keep to the middle of the channel',
      'Have right of way over all power-driven vessels',
      'Anchor if a larger vessel approaches',
    ],
    why: 'Rule 9(b): a vessel of less than 20 metres in length or a sailing vessel shall not impede the passage of a vessel which can safely navigate only within a narrow channel or fairway.',
    source: 'Rule 9(b)',
  },
  {
    id: 'R10',
    q: 'If you have to cross a traffic lane, you shall as far as practicable cross:',
    options: [
      'On a heading as nearly as practicable at right angles to the general direction of traffic flow',
      'At an angle of 45° to the traffic flow',
      'Only at the ends of the lane',
      'At the highest possible speed',
    ],
    why: 'Rule 10(c): a vessel shall, so far as practicable, avoid crossing traffic lanes but if obliged to do so shall cross on a heading as nearly as practicable at right angles to the general direction of traffic flow.',
    source: 'Rule 10(c)',
  },
  {
    id: 'R13b',
    q: 'When is a vessel deemed to be overtaking?',
    options: [
      'When coming up with another vessel from a direction more than 22.5° abaft her beam',
      'When she is faster than the other vessel',
      'When coming up from a direction more than 22.5° forward of her beam',
      'When the other vessel is within 2 nautical miles',
    ],
    why: 'Rule 13(b): a vessel shall be deemed to be overtaking when coming up with another vessel from a direction more than 22.5 degrees abaft her beam – at night she would see only the sternlight.',
    source: 'Rule 13(b)',
  },
  {
    id: 'R13d',
    q: 'You are overtaking another vessel. When does your duty to keep out of her way end?',
    options: [
      'When you are finally past and clear',
      'When the bearing has changed so that it becomes a crossing situation',
      'When you are abeam of her',
      'When she sounds one short blast',
    ],
    why: 'Rule 13(d): any subsequent alteration of the bearing does not make the overtaking vessel a crossing vessel or relieve her of the duty of keeping clear until she is finally past and clear.',
    source: 'Rule 13(d)',
  },
  {
    id: 'R14c',
    q: 'You are in doubt whether a head-on situation exists. What shall you do?',
    options: [
      'Assume that it does exist and act accordingly',
      'Assume that it is a crossing situation',
      'Keep your course and speed until the situation is clear',
      'Alter course to port to make the situation clear',
    ],
    why: 'Rule 14(c): when a vessel is in any doubt as to whether such a situation exists she shall assume that it does exist and act accordingly.',
    source: 'Rule 14(c)',
  },
  {
    id: 'R15',
    q: 'Two power-driven vessels are crossing. Which one keeps out of the way?',
    options: [
      'The one that has the other on her own starboard side',
      'The one that has the other on her own port side',
      'The larger vessel',
      'The faster vessel',
    ],
    why: 'Rule 15: the vessel which has the other on her own starboard side shall keep out of the way and shall, if the circumstances admit, avoid crossing ahead of the other vessel.',
    source: 'Rule 15',
  },
  {
    id: 'R17c',
    q: 'As stand-on vessel in a crossing situation you decide to take action. What should you avoid, if the circumstances admit?',
    options: [
      'Altering course to port for a vessel on your own port side',
      'Altering course to starboard',
      'Reducing speed',
      'Sounding five short blasts',
    ],
    why: 'Rule 17(c): a power-driven vessel which takes action in a crossing situation to avoid collision with another power-driven vessel shall, if the circumstances admit, not alter course to port for a vessel on her own port side.',
    source: 'Rule 17(c)',
  },
  {
    id: 'R18a',
    q: 'Under Rule 18(a), a power-driven vessel underway does NOT have to keep out of the way of which vessel?',
    options: [
      'A vessel constrained by her draught',
      'A vessel not under command',
      'A vessel engaged in fishing',
      'A sailing vessel',
    ],
    why: 'Rule 18(a) lists vessels not under command, restricted in their ability to manoeuvre, engaged in fishing and sailing vessels. A vessel constrained by her draught is covered by Rule 18(d): you shall avoid impeding her safe passage.',
    source: 'Rule 18(a) and (d)',
  },
  {
    id: 'R18b',
    q: 'A sailing vessel underway shall keep out of the way of:',
    options: [
      'A vessel engaged in fishing',
      'A power-driven vessel underway',
      'Any vessel larger than herself',
      'A vessel at anchor only',
    ],
    why: 'Rule 18(b): a sailing vessel underway shall keep out of the way of a vessel not under command, a vessel restricted in her ability to manoeuvre and a vessel engaged in fishing.',
    source: 'Rule 18(b)',
  },
  {
    id: 'R19d',
    q: 'Restricted visibility: a vessel detected by radar alone is forward of your beam and closing. Which action should you avoid?',
    options: [
      'An alteration of course to port (other than for a vessel being overtaken)',
      'An alteration of course to starboard',
      'A reduction of speed',
      'Sounding the fog signal',
    ],
    why: 'Rule 19(d): if possible avoid an alteration of course to port for a vessel forward of the beam, other than for a vessel being overtaken, and an alteration towards a vessel abeam or abaft the beam.',
    source: 'Rule 19(d)',
  },
  {
    id: 'R19e',
    q: 'In restricted visibility you hear the fog signal of another vessel apparently forward of your beam. What shall you do (unless risk of collision does not exist)?',
    options: [
      'Reduce speed to the minimum at which you can keep your course, and take all way off if necessary',
      'Increase speed to get clear quickly',
      'Alter course to port immediately',
      'Keep your course and speed and sound five short blasts',
    ],
    why: 'Rule 19(e): reduce speed to the minimum at which she can be kept on her course, take all her way off if necessary, and navigate with extreme caution until danger of collision is over.',
    source: 'Rule 19(e)',
  },
  {
    id: 'R21a',
    q: 'Over what arc of the horizon does a masthead light show?',
    options: ['225°', '360°', '135°', '112.5°'],
    why: 'Rule 21(a): an unbroken light over an arc of 225 degrees, from right ahead to 22.5 degrees abaft the beam on either side.',
    source: 'Rule 21(a)',
  },
  {
    id: 'R21c',
    q: 'Over what arc of the horizon does a sternlight show?',
    options: ['135°', '225°', '112.5°', '180°'],
    why: 'Rule 21(c): a white light placed as nearly as practicable at the stern, showing an unbroken light over an arc of 135 degrees, 67.5 degrees from right aft on each side.',
    source: 'Rule 21(c)',
  },
  {
    id: 'R22',
    q: 'What is the minimum range of the masthead light of a vessel of 50 metres or more?',
    options: ['6 nautical miles', '3 nautical miles', '5 nautical miles', '2 nautical miles'],
    why: 'Rule 22(a): in vessels of 50 metres or more in length, a masthead light shall be visible at a minimum range of 6 miles; sidelights, sternlight, towing light and all-round lights 3 miles.',
    source: 'Rule 22(a)',
  },
  {
    id: 'R2b',
    q: 'When may you depart from the Rules?',
    options: [
      'When necessary to avoid immediate danger, with due regard to all dangers of navigation and collision',
      'Whenever the master decides it is more convenient',
      'In coastal waters, where local rules always replace the COLREGs',
      'Never, under any circumstances',
    ],
    why: 'Rule 2(b): due regard shall be had to all dangers of navigation and collision and to any special circumstances which may make a departure from these Rules necessary to avoid immediate danger.',
    source: 'Rule 2(b)',
  },
  // ---- Added 7 Oct 2026 – waiting for Robin's review ----
  {
    id: 'R1b',
    q: 'Special rules made by a local authority for a harbour or river shall:',
    options: [
      'Conform as closely as possible to the COLREGs',
      'Always replace the COLREGs completely in that area',
      'Only apply to vessels under 20 metres',
      'Only apply between sunset and sunrise',
    ],
    why: 'Rule 1(b): nothing in these Rules shall interfere with special rules made by an appropriate authority for roadsteads, harbours, rivers, lakes or inland waterways. Such special rules shall conform as closely as possible to these Rules.',
    source: 'Rule 1(b)',
  },
  {
    id: 'R2a',
    q: 'Rule 2(a) – responsibility – says that nothing in the Rules exonerates a vessel from the consequences of neglecting:',
    options: [
      'Any precaution required by the ordinary practice of seamen or by the special circumstances of the case',
      'The instructions from the company only',
      'The VHF watch on channel 16 only',
      'Nothing – following the Rules to the letter is always enough',
    ],
    why: 'Rule 2(a): nothing in these Rules shall exonerate any vessel, or the owner, master or crew, from the consequences of any neglect to comply with these Rules or of the neglect of any precaution which may be required by the ordinary practice of seamen, or by the special circumstances of the case.',
    source: 'Rule 2(a)',
  },
  {
    id: 'R3c',
    q: 'A yacht has her sails up and her engine running ahead. Under the Rules she is:',
    options: [
      'A power-driven vessel',
      'A sailing vessel',
      'A vessel restricted in her ability to manoeuvre',
      'Whichever she chooses to be',
    ],
    why: 'Rule 3(b) and (c): a sailing vessel is any vessel under sail provided that propelling machinery, if fitted, is not being used. Any vessel propelled by machinery is a power-driven vessel. By day she shows a cone, apex downwards (Rule 25(e)).',
    source: 'Rule 3(b), 3(c)',
  },
  {
    id: 'R3d',
    q: 'Which vessel is NOT "engaged in fishing" as defined in Rule 3(d)?',
    options: [
      'A vessel fishing with trolling lines that do not restrict her manoeuvrability',
      'A vessel trawling',
      'A vessel fishing with drift nets',
      'A vessel fishing with long lines that restrict her manoeuvrability',
    ],
    why: 'Rule 3(d): fishing with nets, lines, trawls or other fishing apparatus which restrict manoeuvrability. It does not include a vessel fishing with trolling lines or other fishing apparatus which do not restrict manoeuvrability.',
    source: 'Rule 3(d)',
  },
  {
    id: 'R3h',
    q: 'A vessel constrained by her draught is:',
    options: [
      'A power-driven vessel severely restricted in her ability to deviate from her course because of her draught in relation to the available depth and width of water',
      'Any vessel with a draught of more than 10 metres',
      'A vessel aground',
      'A vessel that cannot manoeuvre because of the nature of her work',
    ],
    why: 'Rule 3(h): a power-driven vessel which, because of her draught in relation to the available depth and width of navigable water, is severely restricted in her ability to deviate from the course she is following.',
    source: 'Rule 3(h)',
  },
  {
    id: 'R3i',
    q: 'When is a vessel "underway"?',
    options: [
      'When she is not at anchor, made fast to the shore or aground',
      'Only when she is making way through the water',
      'Only when her engine is running',
      'When she has a pilot on board',
    ],
    why: 'Rule 3(i): the word "underway" means that a vessel is not at anchor, or made fast to the shore, or aground. A vessel can be underway but not making way.',
    source: 'Rule 3(i)',
  },
  {
    id: 'R3k',
    q: 'When are vessels deemed to be "in sight of one another"?',
    options: [
      'Only when one can be observed visually from the other',
      'When they can see each other on radar',
      'When they are within 2 nautical miles',
      'When they can hear each other’s fog signals',
    ],
    why: 'Rule 3(k): vessels shall be deemed to be in sight of one another only when one can be observed visually from the other.',
    source: 'Rule 3(k)',
  },
  {
    id: 'R3l',
    q: 'Which of these is "restricted visibility" in the sense of Rule 3(l)?',
    options: [
      'Visibility reduced by a heavy rainstorm',
      'Darkness on a clear night',
      'Your view ahead blocked by deck cargo',
      'Sun glare on the water',
    ],
    why: 'Rule 3(l): any condition in which visibility is restricted by fog, mist, falling snow, heavy rainstorms, sandstorms or any other similar causes. Darkness alone is not restricted visibility.',
    source: 'Rule 3(l)',
  },
  {
    id: 'R4',
    q: 'Rules 4–10 (conduct of vessels in any condition of visibility) apply:',
    options: [
      'In any condition of visibility',
      'Only when vessels are in sight of one another',
      'Only in restricted visibility',
      'Only in narrow channels and traffic separation schemes',
    ],
    why: 'Rule 4: the Rules in Section I of Part B apply in any condition of visibility.',
    source: 'Rule 4',
  },
  {
    id: 'R6b',
    q: 'Which extra factor must a vessel with operational radar take into account when deciding a safe speed?',
    options: [
      'The characteristics, efficiency and limitations of the radar equipment',
      'The colour of the radar display',
      'The number of radar operators on the bridge',
      'Nothing – radar means you may keep full speed',
    ],
    why: 'Rule 6(b): vessels with operational radar shall also consider, among other things, the characteristics, efficiency and limitations of the radar equipment, the range scale in use, sea state and weather interference, and that small vessels and ice may not be detected.',
    source: 'Rule 6(b)',
  },
  {
    id: 'R8e',
    q: 'If necessary to avoid collision or to allow more time to assess the situation, a vessel shall:',
    options: [
      'Slacken her speed or take all way off by stopping or reversing her means of propulsion',
      'Increase speed to pass ahead quickly',
      'Call the other vessel on VHF and keep her course and speed',
      'Sound five short blasts and keep her course',
    ],
    why: 'Rule 8(e): if necessary to avoid collision or allow more time to assess the situation, a vessel shall slacken her speed or take all way off by stopping or reversing her means of propulsion.',
    source: 'Rule 8(e)',
  },
  {
    id: 'R8f',
    q: 'A vessel required "not to impede" another vessel shall:',
    options: [
      'Take early action to allow sufficient sea room for the safe passage of the other vessel',
      'Keep her course and speed until the other vessel alters',
      'Only act once risk of collision exists',
      'Ask the other vessel to slow down',
    ],
    why: 'Rule 8(f)(i): a vessel which is required not to impede the passage or safe passage of another vessel shall, when required by the circumstances of the case, take early action to allow sufficient sea room for the safe passage of the other vessel.',
    source: 'Rule 8(f)',
  },
  {
    id: 'R9a',
    q: 'In a narrow channel, a vessel proceeding along the course of the channel shall keep:',
    options: [
      'As near to the outer limit of the channel on her starboard side as is safe and practicable',
      'In the middle of the channel',
      'As near to the outer limit on her port side as is safe',
      'Wherever the water is deepest',
    ],
    why: 'Rule 9(a): a vessel proceeding along the course of a narrow channel or fairway shall keep as near to the outer limit of the channel or fairway which lies on her starboard side as is safe and practicable.',
    source: 'Rule 9(a)',
  },
  {
    id: 'R9d',
    q: 'May you cross a narrow channel?',
    options: [
      'Yes, but not if it impedes a vessel which can safely navigate only within the channel',
      'Never',
      'Only at right angles and only by day',
      'Yes, other vessels must always give way to you',
    ],
    why: 'Rule 9(d): a vessel shall not cross a narrow channel or fairway if such crossing impedes the passage of a vessel which can safely navigate only within such channel or fairway. That vessel may sound five short blasts if in doubt about your intentions.',
    source: 'Rule 9(d)',
  },
  {
    id: 'R9f',
    q: 'You are nearing a bend in a channel where other vessels may be hidden by an obstruction. What shall you do?',
    options: [
      'Navigate with particular alertness and caution and sound one prolonged blast',
      'Sound two prolonged blasts and keep to the middle',
      'Sound five short blasts',
      'Increase speed to get round the bend quickly',
    ],
    why: 'Rule 9(f) and Rule 34(e): approach with particular alertness and caution and sound one prolonged blast. Any vessel round the bend that hears it answers with one prolonged blast.',
    source: 'Rule 9(f), 34(e)',
  },
  {
    id: 'R10b',
    q: 'A vessel using a traffic separation scheme shall:',
    options: [
      'Proceed in the appropriate traffic lane in the general direction of traffic flow for that lane',
      'Use either lane, whichever is less busy',
      'Proceed along the separation zone',
      'Always join at the start of the scheme',
    ],
    why: 'Rule 10(b)(i): proceed in the appropriate traffic lane in the general direction of traffic flow for that lane. As far as practicable keep clear of the separation line or zone, and normally join or leave at the termination of a lane – from the side at as small an angle as practicable.',
    source: 'Rule 10(b)',
  },
  {
    id: 'R10h',
    q: 'A vessel NOT using a traffic separation scheme shall:',
    options: [
      'Avoid it by as wide a margin as is practicable',
      'Keep inside the separation zone',
      'Cross it at a small angle',
      'Follow the traffic in the nearest lane',
    ],
    why: 'Rule 10(h): a vessel not using a traffic separation scheme shall avoid it by as wide a margin as is practicable.',
    source: 'Rule 10(h)',
  },
  {
    id: 'R10i',
    q: 'In a traffic lane, a vessel engaged in fishing:',
    options: [
      'Shall not impede the passage of any vessel following the traffic lane',
      'Has right of way over all vessels in the lane',
      'Is not allowed in the scheme at all',
      'Must follow the general direction of traffic flow at all times',
    ],
    why: 'Rule 10(i): a vessel engaged in fishing shall not impede the passage of any vessel following a traffic lane. Rule 10(j): a vessel under 20 m or a sailing vessel shall not impede the safe passage of a power-driven vessel following a traffic lane.',
    source: 'Rule 10(i)',
  },
  {
    id: 'R12a1',
    q: 'Two sailing vessels approach each other with the wind on different sides. Which one keeps out of the way?',
    options: [
      'The one with the wind on her port side',
      'The one with the wind on her starboard side',
      'The one to windward',
      'The larger one',
    ],
    why: 'Rule 12(a)(i): when each has the wind on a different side, the vessel which has the wind on the port side shall keep out of the way of the other.',
    source: 'Rule 12(a)(i)',
  },
  {
    id: 'R12a2',
    q: 'Two sailing vessels have the wind on the same side. Which one keeps out of the way?',
    options: [
      'The vessel to windward',
      'The vessel to leeward',
      'The faster vessel',
      'The vessel on the other’s port side',
    ],
    why: 'Rule 12(a)(ii): when both have the wind on the same side, the vessel which is to windward shall keep out of the way of the vessel which is to leeward.',
    source: 'Rule 12(a)(ii)',
  },
  {
    id: 'R12b',
    q: 'For Rule 12, the windward side of a sailing vessel is:',
    options: [
      'The side opposite to that on which the mainsail is carried',
      'The side on which the mainsail is carried',
      'Always the starboard side',
      'The side facing the nearest land',
    ],
    why: 'Rule 12(b): the windward side shall be deemed to be the side opposite to that on which the mainsail is carried (in a square-rigged vessel, the largest fore-and-aft sail).',
    source: 'Rule 12(b)',
  },
  {
    id: 'R13a',
    q: 'A sailing vessel is overtaking a power-driven vessel. Who keeps out of the way?',
    options: [
      'The sailing vessel – she is overtaking',
      'The power-driven vessel – sail has right of way',
      'Both vessels alter to starboard',
      'The larger vessel',
    ],
    why: 'Rule 13(a): notwithstanding anything in Rules 4–18, any vessel overtaking any other shall keep out of the way of the vessel being overtaken. Rule 18 does not change that.',
    source: 'Rule 13(a)',
  },
  {
    id: 'R13c',
    q: 'You are in doubt whether you are overtaking another vessel. What shall you assume?',
    options: [
      'That you are overtaking, and act accordingly',
      'That it is a crossing situation and you are stand-on',
      'That it is a head-on situation',
      'Nothing until the bearing has changed',
    ],
    why: 'Rule 13(c): when a vessel is in any doubt as to whether she is overtaking another, she shall assume that this is the case and act accordingly.',
    source: 'Rule 13(c)',
  },
  {
    id: 'R14a',
    q: 'In a head-on situation between two power-driven vessels:',
    options: [
      'Each alters course to starboard so that they pass port to port',
      'Each alters course to port so that they pass starboard to starboard',
      'The larger vessel keeps her course and the smaller gives way',
      'The vessel with the other on her starboard side gives way and the other stands on',
    ],
    why: 'Rule 14(a): when two power-driven vessels are meeting on reciprocal or nearly reciprocal courses so as to involve risk of collision, each shall alter her course to starboard so that each shall pass on the port side of the other.',
    source: 'Rule 14(a)',
  },
  {
    id: 'R14b',
    q: 'At night, how do you know you are in a head-on situation?',
    options: [
      'You see the other vessel’s masthead lights in a line or nearly in a line and/or both sidelights',
      'You see her green sidelight only',
      'You see her sternlight',
      'You see her red sidelight only',
    ],
    why: 'Rule 14(b): such a situation shall be deemed to exist when a vessel sees the other ahead or nearly ahead and by night she could see the masthead lights of the other in a line or nearly in a line and/or both sidelights, and by day the corresponding aspect.',
    source: 'Rule 14(b)',
  },
  {
    id: 'R16',
    q: 'What does Rule 16 require of the give-way vessel?',
    options: [
      'Take early and substantial action to keep well clear',
      'Keep course and speed',
      'Take small alterations so as not to confuse the other vessel',
      'Wait until the stand-on vessel has acted',
    ],
    why: 'Rule 16: every vessel which is directed to keep out of the way of another vessel shall, so far as possible, take early and substantial action to keep well clear.',
    source: 'Rule 16',
  },
  {
    id: 'R17a',
    q: 'As stand-on vessel, when MAY you take action to avoid collision by your manoeuvre alone?',
    options: [
      'As soon as it becomes apparent that the give-way vessel is not taking appropriate action',
      'Never – the stand-on vessel must always keep course and speed',
      'Only after the vessels have collided',
      'Whenever you want to, as early as possible',
    ],
    why: 'Rule 17(a)(ii): the stand-on vessel may take action to avoid collision by her manoeuvre alone as soon as it becomes apparent to her that the vessel required to keep out of the way is not taking appropriate action.',
    source: 'Rule 17(a)(ii)',
  },
  {
    id: 'R17b',
    q: 'As stand-on vessel you find yourself so close that collision cannot be avoided by the action of the give-way vessel alone. You shall:',
    options: [
      'Take such action as will best aid to avoid collision',
      'Keep course and speed – it is her responsibility',
      'Only sound five short blasts',
      'Only call her on VHF',
    ],
    why: 'Rule 17(b): when the stand-on vessel finds herself so close that collision cannot be avoided by the action of the give-way vessel alone, she shall take such action as will best aid to avoid collision.',
    source: 'Rule 17(b)',
  },
  {
    id: 'R18d',
    q: 'Which vessels shall, if the circumstances admit, avoid impeding the safe passage of a vessel constrained by her draught?',
    options: [
      'Any vessel other than one not under command or restricted in her ability to manoeuvre',
      'Only power-driven vessels',
      'Only vessels under 20 metres',
      'No vessel – constrained by draught has no special status',
    ],
    why: 'Rule 18(d)(i): any vessel other than a vessel not under command or a vessel restricted in her ability to manoeuvre shall, if the circumstances of the case admit, avoid impeding the safe passage of a vessel constrained by her draught, exhibiting the signals in Rule 28.',
    source: 'Rule 18(d)',
  },
  {
    id: 'R19a',
    q: 'When does Rule 19 apply?',
    options: [
      'To vessels not in sight of one another when navigating in or near an area of restricted visibility',
      'To all vessels at night',
      'Only when two vessels can see each other in fog',
      'Only to vessels without radar',
    ],
    why: 'Rule 19(a): this Rule applies to vessels not in sight of one another when navigating in or near an area of restricted visibility.',
    source: 'Rule 19(a)',
  },
  {
    id: 'R19b',
    q: 'In restricted visibility, a power-driven vessel shall have her engines:',
    options: [
      'Ready for immediate manoeuvre',
      'Stopped',
      'At full sea speed to get through quickly',
      'On automatic control with the bridge unmanned',
    ],
    why: 'Rule 19(b): every vessel shall proceed at a safe speed adapted to the prevailing circumstances and conditions of restricted visibility. A power-driven vessel shall have her engines ready for immediate manoeuvre.',
    source: 'Rule 19(b)',
  },
  {
    id: 'R20b',
    q: 'When shall the navigation lights be shown?',
    options: [
      'From sunset to sunrise, and in restricted visibility also from sunrise to sunset',
      'Only from sunset to sunrise',
      'Only in restricted visibility',
      'Only when other vessels are in sight',
    ],
    why: 'Rule 20(b): the lights shall be shown from sunset to sunrise. Rule 20(c): they shall also be shown from sunrise to sunset in restricted visibility, and may be shown in all other circumstances when it is deemed necessary.',
    source: 'Rule 20(b), 20(c)',
  },
  {
    id: 'R21b',
    q: 'Over what arc does each sidelight show?',
    options: [
      '112.5° – from right ahead to 22.5° abaft the beam on its side',
      '135° – from right aft to the beam',
      '225° – from right ahead to abaft the beam on both sides',
      '90° – from right ahead to the beam',
    ],
    why: 'Rule 21(b): sidelights mean a green light on the starboard side and a red light on the port side, each showing an unbroken light over an arc of 112.5 degrees, from right ahead to 22.5 degrees abaft the beam on its side.',
    source: 'Rule 21(b)',
  },
  {
    id: 'R22b',
    q: 'What is the minimum range of the sidelights of a vessel of 50 metres or more?',
    options: ['3 nautical miles', '6 nautical miles', '2 nautical miles', '1 nautical mile'],
    why: 'Rule 22(a): in vessels of 50 metres or more, masthead light 6 miles; sidelights, sternlight, towing light and all-round lights 3 miles.',
    source: 'Rule 22(a)',
  },
  {
    id: 'R36',
    q: 'Which signal should you avoid when trying to attract the attention of another vessel?',
    options: [
      'High-intensity intermittent or revolving lights, such as strobe lights',
      'Directing a searchlight beam in the direction of the danger',
      'A light or sound signal that cannot be mistaken for any signal in the Rules',
      'Calling her on VHF',
    ],
    why: 'Rule 36: you may make light or sound signals that cannot be mistaken for any signal authorized elsewhere in the Rules, or direct a searchlight beam in the direction of the danger. Any light to attract attention shall be such that it cannot be mistaken for an aid to navigation; high-intensity intermittent or revolving lights, such as strobe lights, shall be avoided.',
    source: 'Rule 36',
  },
]
