import type { TheoryItem } from '../study/generators/theory'

// COLREG theory questions. The first option is the correct one; the app shuffles them.
// Every question names its rule so it can be checked against the text.

export const COLREGS_THEORY: (TheoryItem & { id: string })[] = [
  {
    id: 'R5',
    q: 'Rule 5 requires every vessel to keep a proper look-out by:',
    options: [
      'Sight and hearing, and all available means appropriate in the circumstances',
      'Radar only, when the visibility is restricted',
      'Sight only, from the bridge',
      'Sight and hearing, but only at night',
    ],
    why: 'Rule 5: a proper look-out by sight and hearing as well as by all available means appropriate in the prevailing circumstances and conditions.',
    source: 'Rule 5',
  },
  {
    id: 'R6',
    q: 'According to Rule 6, a safe speed is a speed at which you can:',
    options: [
      'Take proper and effective action to avoid collision and be stopped within a distance appropriate to the circumstances',
      'Always stop within your own length',
      'Keep to the speed limit shown on the chart',
      'Maintain steerage way and nothing more',
    ],
    why: 'Rule 6: every vessel shall at all times proceed at a safe speed so that she can take proper and effective action to avoid collision and be stopped within a distance appropriate to the prevailing circumstances and conditions.',
    source: 'Rule 6',
  },
  {
    id: 'R7d',
    q: 'Which observation means that risk of collision shall be deemed to exist?',
    options: [
      'The compass bearing of an approaching vessel does not appreciably change',
      'The relative bearing of the other vessel changes quickly',
      'You can see her sternlight',
      'She is more than 6 nautical miles away',
    ],
    why: 'Rule 7(d)(i): such risk shall be deemed to exist if the compass bearing of an approaching vessel does not appreciably change. It may sometimes exist even when an appreciable bearing change is evident, especially with a very large vessel, a tow or at close range.',
    source: 'Rule 7(d)',
  },
  {
    id: 'R7c',
    q: 'What does Rule 7 warn you against?',
    options: [
      'Making assumptions on the basis of scanty information, especially scanty radar information',
      'Using radar in clear weather',
      'Taking bearings with a gyro compass',
      'Calling other vessels on VHF',
    ],
    why: 'Rule 7(c): assumptions shall not be made on the basis of scanty information, especially scanty radar information.',
    source: 'Rule 7(c)',
  },
  {
    id: 'R8',
    q: 'What does Rule 8 say about alterations of course and speed to avoid collision?',
    options: [
      'They should be large enough to be readily apparent to another vessel; avoid a succession of small alterations',
      'They should be small, so that the other vessel is not confused',
      'Only alterations of course are allowed, never of speed',
      'They should be made as late as possible',
    ],
    why: 'Rule 8(b): any alteration of course and/or speed should, if the circumstances admit, be large enough to be readily apparent to another vessel observing visually or by radar; a succession of small alterations should be avoided.',
    source: 'Rule 8(b)',
  },
  {
    id: 'R9',
    q: 'In a narrow channel, a vessel of less than 20 m or a sailing vessel shall:',
    options: [
      'Not impede the passage of a vessel which can safely navigate only within the channel',
      'Always keep to the middle of the channel',
      'Have right of way over all power-driven vessels',
      'Anchor if a larger vessel approaches',
    ],
    why: 'Rule 9(b): a vessel of less than 20 metres in length or a sailing vessel shall not impede the passage of a vessel which can safely navigate only within a narrow channel or fairway.',
    source: 'Rule 9(b)',
  },
  {
    id: 'R10',
    q: 'If you have to cross a traffic lane, you shall as far as practicable cross:',
    options: [
      'On a heading as nearly as practicable at right angles to the general direction of traffic flow',
      'At an angle of 45° to the traffic flow',
      'Only at the ends of the lane',
      'At the highest possible speed',
    ],
    why: 'Rule 10(c): a vessel shall, so far as practicable, avoid crossing traffic lanes but if obliged to do so shall cross on a heading as nearly as practicable at right angles to the general direction of traffic flow.',
    source: 'Rule 10(c)',
  },
  {
    id: 'R13b',
    q: 'When is a vessel deemed to be overtaking?',
    options: [
      'When coming up with another vessel from a direction more than 22.5° abaft her beam',
      'When she is faster than the other vessel',
      'When coming up from a direction more than 22.5° forward of her beam',
      'When the other vessel is within 2 nautical miles',
    ],
    why: 'Rule 13(b): a vessel shall be deemed to be overtaking when coming up with another vessel from a direction more than 22.5 degrees abaft her beam – at night she would see only the sternlight.',
    source: 'Rule 13(b)',
  },
  {
    id: 'R13d',
    q: 'You are overtaking another vessel. When does your duty to keep out of her way end?',
    options: [
      'When you are finally past and clear',
      'When the bearing has changed so that it becomes a crossing situation',
      'When you are abeam of her',
      'When she sounds one short blast',
    ],
    why: 'Rule 13(d): any subsequent alteration of the bearing does not make the overtaking vessel a crossing vessel or relieve her of the duty of keeping clear until she is finally past and clear.',
    source: 'Rule 13(d)',
  },
  {
    id: 'R14c',
    q: 'You are in doubt whether a head-on situation exists. What shall you do?',
    options: [
      'Assume that it does exist and act accordingly',
      'Assume that it is a crossing situation',
      'Keep your course and speed until the situation is clear',
      'Alter course to port to make the situation clear',
    ],
    why: 'Rule 14(c): when a vessel is in any doubt as to whether such a situation exists she shall assume that it does exist and act accordingly.',
    source: 'Rule 14(c)',
  },
  {
    id: 'R15',
    q: 'Two power-driven vessels are crossing. Which one keeps out of the way?',
    options: [
      'The one that has the other on her own starboard side',
      'The one that has the other on her own port side',
      'The larger vessel',
      'The faster vessel',
    ],
    why: 'Rule 15: the vessel which has the other on her own starboard side shall keep out of the way and shall, if the circumstances admit, avoid crossing ahead of the other vessel.',
    source: 'Rule 15',
  },
  {
    id: 'R17c',
    q: 'As stand-on vessel in a crossing situation you decide to take action. What should you avoid, if the circumstances admit?',
    options: [
      'Altering course to port for a vessel on your own port side',
      'Altering course to starboard',
      'Reducing speed',
      'Sounding five short blasts',
    ],
    why: 'Rule 17(c): a power-driven vessel which takes action in a crossing situation to avoid collision with another power-driven vessel shall, if the circumstances admit, not alter course to port for a vessel on her own port side.',
    source: 'Rule 17(c)',
  },
  {
    id: 'R18a',
    q: 'Under Rule 18(a), a power-driven vessel underway does NOT have to keep out of the way of which vessel?',
    options: [
      'A vessel constrained by her draught',
      'A vessel not under command',
      'A vessel engaged in fishing',
      'A sailing vessel',
    ],
    why: 'Rule 18(a) lists vessels not under command, restricted in their ability to manoeuvre, engaged in fishing and sailing vessels. A vessel constrained by her draught is covered by Rule 18(d): you shall avoid impeding her safe passage.',
    source: 'Rule 18(a) and (d)',
  },
  {
    id: 'R18b',
    q: 'A sailing vessel underway shall keep out of the way of:',
    options: [
      'A vessel engaged in fishing',
      'A power-driven vessel underway',
      'Any vessel larger than herself',
      'A vessel at anchor only',
    ],
    why: 'Rule 18(b): a sailing vessel underway shall keep out of the way of a vessel not under command, a vessel restricted in her ability to manoeuvre and a vessel engaged in fishing.',
    source: 'Rule 18(b)',
  },
  {
    id: 'R19d',
    q: 'Restricted visibility: a vessel detected by radar alone is forward of your beam and closing. Which action should you avoid?',
    options: [
      'An alteration of course to port (other than for a vessel being overtaken)',
      'An alteration of course to starboard',
      'A reduction of speed',
      'Sounding the fog signal',
    ],
    why: 'Rule 19(d): if possible avoid an alteration of course to port for a vessel forward of the beam, other than for a vessel being overtaken, and an alteration towards a vessel abeam or abaft the beam.',
    source: 'Rule 19(d)',
  },
  {
    id: 'R19e',
    q: 'In restricted visibility you hear the fog signal of another vessel apparently forward of your beam. What shall you do (unless risk of collision does not exist)?',
    options: [
      'Reduce speed to the minimum at which you can keep your course, and take all way off if necessary',
      'Increase speed to get clear quickly',
      'Alter course to port immediately',
      'Keep your course and speed and sound five short blasts',
    ],
    why: 'Rule 19(e): reduce speed to the minimum at which she can be kept on her course, take all her way off if necessary, and navigate with extreme caution until danger of collision is over.',
    source: 'Rule 19(e)',
  },
  {
    id: 'R21a',
    q: 'Over what arc of the horizon does a masthead light show?',
    options: ['225°', '360°', '135°', '112.5°'],
    why: 'Rule 21(a): an unbroken light over an arc of 225 degrees, from right ahead to 22.5 degrees abaft the beam on either side.',
    source: 'Rule 21(a)',
  },
  {
    id: 'R21c',
    q: 'Over what arc of the horizon does a sternlight show?',
    options: ['135°', '225°', '112.5°', '180°'],
    why: 'Rule 21(c): a white light placed as nearly as practicable at the stern, showing an unbroken light over an arc of 135 degrees, 67.5 degrees from right aft on each side.',
    source: 'Rule 21(c)',
  },
  {
    id: 'R22',
    q: 'What is the minimum range of the masthead light of a vessel of 50 metres or more?',
    options: ['6 nautical miles', '3 nautical miles', '5 nautical miles', '2 nautical miles'],
    why: 'Rule 22(a): in vessels of 50 metres or more in length, a masthead light shall be visible at a minimum range of 6 miles; sidelights, sternlight, towing light and all-round lights 3 miles.',
    source: 'Rule 22(a)',
  },
  {
    id: 'R2b',
    q: 'When may you depart from the Rules?',
    options: [
      'When necessary to avoid immediate danger, with due regard to all dangers of navigation and collision',
      'Whenever the master decides it is more convenient',
      'In coastal waters, where local rules always replace the COLREGs',
      'Never, under any circumstances',
    ],
    why: 'Rule 2(b): due regard shall be had to all dangers of navigation and collision and to any special circumstances which may make a departure from these Rules necessary to avoid immediate danger.',
    source: 'Rule 2(b)',
  },
  // ---- Added 7 Oct 2026 – waiting for Robin's review ----
  {
    id: 'R1b',
    q: 'Special rules made by a local authority for a harbour or river shall:',
    options: [
      'Conform as closely as possible to the COLREGs',
      'Always replace the COLREGs completely in that area',
      'Only apply to vessels under 20 metres',
      'Only apply between sunset and sunrise',
    ],
    why: 'Rule 1(b): nothing in these Rules shall interfere with special rules made by an appropriate authority for roadsteads, harbours, rivers, lakes or inland waterways. Such special rules shall conform as closely as possible to these Rules.',
    source: 'Rule 1(b)',
  },
  {
    id: 'R2a',
    q: 'Rule 2(a) – responsibility – says that nothing in the Rules exonerates a vessel from the consequences of neglecting:',
    options: [
      'Any precaution required by the ordinary practice of seamen or by the special circumstances of the case',
      'The instructions from the company only',
      'The VHF watch on channel 16 only',
      'Nothing – following the Rules to the letter is always enough',
    ],
    why: 'Rule 2(a): nothing in these Rules shall exonerate any vessel, or the owner, master or crew, from the consequences of any neglect to comply with these Rules or of the neglect of any precaution which may be required by the ordinary practice of seamen, or by the special circumstances of the case.',
    source: 'Rule 2(a)',
  },
  {
    id: 'R3c',
    q: 'A yacht has her sails up and her engine running ahead. Under the Rules she is:',
    options: [
      'A power-driven vessel',
      'A sailing vessel',
      'A vessel restricted in her ability to manoeuvre',
      'Whichever she chooses to be',
    ],
    why: 'Rule 3(b) and (c): a sailing vessel is any vessel under sail provided that propelling machinery, if fitted, is not being used. Any vessel propelled by machinery is a power-driven vessel. By day she shows a cone, apex downwards (Rule 25(e)).',
    source: 'Rule 3(b), 3(c)',
  },
  {
    id: 'R3d',
    q: 'Which vessel is NOT "engaged in fishing" as defined in Rule 3(d)?',
    options: [
      'A vessel fishing with trolling lines that do not restrict her manoeuvrability',
      'A vessel trawling',
      'A vessel fishing with drift nets',
      'A vessel fishing with long lines that restrict her manoeuvrability',
    ],
    why: 'Rule 3(d): fishing with nets, lines, trawls or other fishing apparatus which restrict manoeuvrability. It does not include a vessel fishing with trolling lines or other fishing apparatus which do not restrict manoeuvrability.',
    source: 'Rule 3(d)',
  },
  {
    id: 'R3h',
    q: 'A vessel constrained by her draught is:',
    options: [
      'A power-driven vessel severely restricted in her ability to deviate from her course because of her draught in relation to the available depth and width of water',
      'Any vessel with a draught of more than 10 metres',
      'A vessel aground',
      'A vessel that cannot manoeuvre because of the nature of her work',
    ],
    why: 'Rule 3(h): a power-driven vessel which, because of her draught in relation to the available depth and width of navigable water, is severely restricted in her ability to deviate from the course she is following.',
    source: 'Rule 3(h)',
  },
  {
    id: 'R3i',
    q: 'When is a vessel "underway"?',
    options: [
      'When she is not at anchor, made fast to the shore or aground',
      'Only when she is making way through the water',
      'Only when her engine is running',
      'When she has a pilot on board',
    ],
    why: 'Rule 3(i): the word "underway" means that a vessel is not at anchor, or made fast to the shore, or aground. A vessel can be underway but not making way.',
    source: 'Rule 3(i)',
  },
  {
    id: 'R3k',
    q: 'When are vessels deemed to be "in sight of one another"?',
    options: [
      'Only when one can be observed visually from the other',
      'When they can see each other on radar',
      'When they are within 2 nautical miles',
      'When they can hear each other’s fog signals',
    ],
    why: 'Rule 3(k): vessels shall be deemed to be in sight of one another only when one can be observed visually from the other.',
    source: 'Rule 3(k)',
  },
  {
    id: 'R3l',
    q: 'Which of these is "restricted visibility" in the sense of Rule 3(l)?',
    options: [
      'Visibility reduced by a heavy rainstorm',
      'Darkness on a clear night',
      'Your view ahead blocked by deck cargo',
      'Sun glare on the water',
    ],
    why: 'Rule 3(l): any condition in which visibility is restricted by fog, mist, falling snow, heavy rainstorms, sandstorms or any other similar causes. Darkness alone is not restricted visibility.',
    source: 'Rule 3(l)',
  },
  {
    id: 'R4',
    q: 'Rules 4–10 (conduct of vessels in any condition of visibility) apply:',
    options: [
      'In any condition of visibility',
      'Only when vessels are in sight of one another',
      'Only in restricted visibility',
      'Only in narrow channels and traffic separation schemes',
    ],
    why: 'Rule 4: the Rules in Section I of Part B apply in any condition of visibility.',
    source: 'Rule 4',
  },
  {
    id: 'R6b',
    q: 'Which extra factor must a vessel with operational radar take into account when deciding a safe speed?',
    options: [
      'The characteristics, efficiency and limitations of the radar equipment',
      'The colour of the radar display',
      'The number of radar operators on the bridge',
      'Nothing – radar means you may keep full speed',
    ],
    why: 'Rule 6(b): vessels with operational radar shall also consider, among other things, the characteristics, efficiency and limitations of the radar equipment, the range scale in use, sea state and weather interference, and that small vessels and ice may not be detected.',
    source: 'Rule 6(b)',
  },
  {
    id: 'R8e',
    q: 'If necessary to avoid collision or to allow more time to assess the situation, a vessel shall:',
    options: [
      'Slacken her speed or take all way off by stopping or reversing her means of propulsion',
      'Increase speed to pass ahead quickly',
      'Call the other vessel on VHF and keep her course and speed',
      'Sound five short blasts and keep her course',
    ],
    why: 'Rule 8(e): if necessary to avoid collision or allow more time to assess the situation, a vessel shall slacken her speed or take all way off by stopping or reversing her means of propulsion.',
    source: 'Rule 8(e)',
  },
  {
    id: 'R8f',
    q: 'A vessel required "not to impede" another vessel shall:',
    options: [
      'Take early action to allow sufficient sea room for the safe passage of the other vessel',
      'Keep her course and speed until the other vessel alters',
      'Only act once risk of collision exists',
      'Ask the other vessel to slow down',
    ],
    why: 'Rule 8(f)(i): a vessel which is required not to impede the passage or safe passage of another vessel shall, when required by the circumstances of the case, take early action to allow sufficient sea room for the safe passage of the other vessel.',
    source: 'Rule 8(f)',
  },
  {
    id: 'R9a',
    q: 'In a narrow channel, a vessel proceeding along the course of the channel shall keep:',
    options: [
      'As near to the outer limit of the channel on her starboard side as is safe and practicable',
      'In the middle of the channel',
      'As near to the outer limit on her port side as is safe',
      'Wherever the water is deepest',
    ],
    why: 'Rule 9(a): a vessel proceeding along the course of a narrow channel or fairway shall keep as near to the outer limit of the channel or fairway which lies on her starboard side as is safe and practicable.',
    source: 'Rule 9(a)',
  },
  {
    id: 'R9d',
    q: 'May you cross a narrow channel?',
    options: [
      'Yes, but not if it impedes a vessel which can safely navigate only within the channel',
      'Never',
      'Only at right angles and only by day',
      'Yes, other vessels must always give way to you',
    ],
    why: 'Rule 9(d): a vessel shall not cross a narrow channel or fairway if such crossing impedes the passage of a vessel which can safely navigate only within such channel or fairway. That vessel may sound five short blasts if in doubt about your intentions.',
    source: 'Rule 9(d)',
  },
  {
    id: 'R9f',
    q: 'You are nearing a bend in a channel where other vessels may be hidden by an obstruction. What shall you do?',
    options: [
      'Navigate with particular alertness and caution and sound one prolonged blast',
      'Sound two prolonged blasts and keep to the middle',
      'Sound five short blasts',
      'Increase speed to get round the bend quickly',
    ],
    why: 'Rule 9(f) and Rule 34(e): approach with particular alertness and caution and sound one prolonged blast. Any vessel round the bend that hears it answers with one prolonged blast.',
    source: 'Rule 9(f), 34(e)',
  },
  {
    id: 'R10b',
    q: 'A vessel using a traffic separation scheme shall:',
    options: [
      'Proceed in the appropriate traffic lane in the general direction of traffic flow for that lane',
      'Use either lane, whichever is less busy',
      'Proceed along the separation zone',
      'Always join at the start of the scheme',
    ],
    why: 'Rule 10(b)(i): proceed in the appropriate traffic lane in the general direction of traffic flow for that lane. As far as practicable keep clear of the separation line or zone, and normally join or leave at the termination of a lane – from the side at as small an angle as practicable.',
    source: 'Rule 10(b)',
  },
  {
    id: 'R10h',
    q: 'A vessel NOT using a traffic separation scheme shall:',
    options: [
      'Avoid it by as wide a margin as is practicable',
      'Keep inside the separation zone',
      'Cross it at a small angle',
      'Follow the traffic in the nearest lane',
    ],
    why: 'Rule 10(h): a vessel not using a traffic separation scheme shall avoid it by as wide a margin as is practicable.',
    source: 'Rule 10(h)',
  },
  {
    id: 'R10i',
    q: 'In a traffic lane, a vessel engaged in fishing:',
    options: [
      'Shall not impede the passage of any vessel following the traffic lane',
      'Has right of way over all vessels in the lane',
      'Is not allowed in the scheme at all',
      'Must follow the general direction of traffic flow at all times',
    ],
    why: 'Rule 10(i): a vessel engaged in fishing shall not impede the passage of any vessel following a traffic lane. Rule 10(j): a vessel under 20 m or a sailing vessel shall not impede the safe passage of a power-driven vessel following a traffic lane.',
    source: 'Rule 10(i)',
  },
  {
    id: 'R12a1',
    q: 'Two sailing vessels approach each other with the wind on different sides. Which one keeps out of the way?',
    options: [
      'The one with the wind on her port side',
      'The one with the wind on her starboard side',
      'The one to windward',
      'The larger one',
    ],
    why: 'Rule 12(a)(i): when each has the wind on a different side, the vessel which has the wind on the port side shall keep out of the way of the other.',
    source: 'Rule 12(a)(i)',
  },
  {
    id: 'R12a2',
    q: 'Two sailing vessels have the wind on the same side. Which one keeps out of the way?',
    options: [
      'The vessel to windward',
      'The vessel to leeward',
      'The faster vessel',
      'The vessel on the other’s port side',
    ],
    why: 'Rule 12(a)(ii): when both have the wind on the same side, the vessel which is to windward shall keep out of the way of the vessel which is to leeward.',
    source: 'Rule 12(a)(ii)',
  },
  {
    id: 'R12b',
    q: 'For Rule 12, the windward side of a sailing vessel is:',
    options: [
      'The side opposite to that on which the mainsail is carried',
      'The side on which the mainsail is carried',
      'Always the starboard side',
      'The side facing the nearest land',
    ],
    why: 'Rule 12(b): the windward side shall be deemed to be the side opposite to that on which the mainsail is carried (in a square-rigged vessel, the largest fore-and-aft sail).',
    source: 'Rule 12(b)',
  },
  {
    id: 'R13a',
    q: 'A sailing vessel is overtaking a power-driven vessel. Who keeps out of the way?',
    options: [
      'The sailing vessel – she is overtaking',
      'The power-driven vessel – sail has right of way',
      'Both vessels alter to starboard',
      'The larger vessel',
    ],
    why: 'Rule 13(a): notwithstanding anything in Rules 4–18, any vessel overtaking any other shall keep out of the way of the vessel being overtaken. Rule 18 does not change that.',
    source: 'Rule 13(a)',
  },
  {
    id: 'R13c',
    q: 'You are in doubt whether you are overtaking another vessel. What shall you assume?',
    options: [
      'That you are overtaking, and act accordingly',
      'That it is a crossing situation and you are stand-on',
      'That it is a head-on situation',
      'Nothing until the bearing has changed',
    ],
    why: 'Rule 13(c): when a vessel is in any doubt as to whether she is overtaking another, she shall assume that this is the case and act accordingly.',
    source: 'Rule 13(c)',
  },
  {
    id: 'R14a',
    q: 'In a head-on situation between two power-driven vessels:',
    options: [
      'Each alters course to starboard so that they pass port to port',
      'Each alters course to port so that they pass starboard to starboard',
      'The larger vessel keeps her course and the smaller gives way',
      'The vessel with the other on her starboard side gives way and the other stands on',
    ],
    why: 'Rule 14(a): when two power-driven vessels are meeting on reciprocal or nearly reciprocal courses so as to involve risk of collision, each shall alter her course to starboard so that each shall pass on the port side of the other.',
    source: 'Rule 14(a)',
  },
  {
    id: 'R14b',
    q: 'At night, how do you know you are in a head-on situation?',
    options: [
      'You see the other vessel’s masthead lights in a line or nearly in a line and/or both sidelights',
      'You see her green sidelight only',
      'You see her sternlight',
      'You see her red sidelight only',
    ],
    why: 'Rule 14(b): such a situation shall be deemed to exist when a vessel sees the other ahead or nearly ahead and by night she could see the masthead lights of the other in a line or nearly in a line and/or both sidelights, and by day the corresponding aspect.',
    source: 'Rule 14(b)',
  },
  {
    id: 'R16',
    q: 'What does Rule 16 require of the give-way vessel?',
    options: [
      'Take early and substantial action to keep well clear',
      'Keep course and speed',
      'Take small alterations so as not to confuse the other vessel',
      'Wait until the stand-on vessel has acted',
    ],
    why: 'Rule 16: every vessel which is directed to keep out of the way of another vessel shall, so far as possible, take early and substantial action to keep well clear.',
    source: 'Rule 16',
  },
  {
    id: 'R17a',
    q: 'As stand-on vessel, when MAY you take action to avoid collision by your manoeuvre alone?',
    options: [
      'As soon as it becomes apparent that the give-way vessel is not taking appropriate action',
      'Never – the stand-on vessel must always keep course and speed',
      'Only after the vessels have collided',
      'Whenever you want to, as early as possible',
    ],
    why: 'Rule 17(a)(ii): the stand-on vessel may take action to avoid collision by her manoeuvre alone as soon as it becomes apparent to her that the vessel required to keep out of the way is not taking appropriate action.',
    source: 'Rule 17(a)(ii)',
  },
  {
    id: 'R17b',
    q: 'As stand-on vessel you find yourself so close that collision cannot be avoided by the action of the give-way vessel alone. You shall:',
    options: [
      'Take such action as will best aid to avoid collision',
      'Keep course and speed – it is her responsibility',
      'Only sound five short blasts',
      'Only call her on VHF',
    ],
    why: 'Rule 17(b): when the stand-on vessel finds herself so close that collision cannot be avoided by the action of the give-way vessel alone, she shall take such action as will best aid to avoid collision.',
    source: 'Rule 17(b)',
  },
  {
    id: 'R18d',
    q: 'Which vessels shall, if the circumstances admit, avoid impeding the safe passage of a vessel constrained by her draught?',
    options: [
      'Any vessel other than one not under command or restricted in her ability to manoeuvre',
      'Only power-driven vessels',
      'Only vessels under 20 metres',
      'No vessel – constrained by draught has no special status',
    ],
    why: 'Rule 18(d)(i): any vessel other than a vessel not under command or a vessel restricted in her ability to manoeuvre shall, if the circumstances of the case admit, avoid impeding the safe passage of a vessel constrained by her draught, exhibiting the signals in Rule 28.',
    source: 'Rule 18(d)',
  },
  {
    id: 'R19a',
    q: 'When does Rule 19 apply?',
    options: [
      'To vessels not in sight of one another when navigating in or near an area of restricted visibility',
      'To all vessels at night',
      'Only when two vessels can see each other in fog',
      'Only to vessels without radar',
    ],
    why: 'Rule 19(a): this Rule applies to vessels not in sight of one another when navigating in or near an area of restricted visibility.',
    source: 'Rule 19(a)',
  },
  {
    id: 'R19b',
    q: 'In restricted visibility, a power-driven vessel shall have her engines:',
    options: [
      'Ready for immediate manoeuvre',
      'Stopped',
      'At full sea speed to get through quickly',
      'On automatic control with the bridge unmanned',
    ],
    why: 'Rule 19(b): every vessel shall proceed at a safe speed adapted to the prevailing circumstances and conditions of restricted visibility. A power-driven vessel shall have her engines ready for immediate manoeuvre.',
    source: 'Rule 19(b)',
  },
  {
    id: 'R20b',
    q: 'When shall the navigation lights be shown?',
    options: [
      'From sunset to sunrise, and in restricted visibility also from sunrise to sunset',
      'Only from sunset to sunrise',
      'Only in restricted visibility',
      'Only when other vessels are in sight',
    ],
    why: 'Rule 20(b): the lights shall be shown from sunset to sunrise. Rule 20(c): they shall also be shown from sunrise to sunset in restricted visibility, and may be shown in all other circumstances when it is deemed necessary.',
    source: 'Rule 20(b), 20(c)',
  },
  {
    id: 'R21b',
    q: 'Over what arc does each sidelight show?',
    options: [
      '112.5° – from right ahead to 22.5° abaft the beam on its side',
      '135° – from right aft to the beam',
      '225° – from right ahead to abaft the beam on both sides',
      '90° – from right ahead to the beam',
    ],
    why: 'Rule 21(b): sidelights mean a green light on the starboard side and a red light on the port side, each showing an unbroken light over an arc of 112.5 degrees, from right ahead to 22.5 degrees abaft the beam on its side.',
    source: 'Rule 21(b)',
  },
  {
    id: 'R22b',
    q: 'What is the minimum range of the sidelights of a vessel of 50 metres or more?',
    options: ['3 nautical miles', '6 nautical miles', '2 nautical miles', '1 nautical mile'],
    why: 'Rule 22(a): in vessels of 50 metres or more, masthead light 6 miles; sidelights, sternlight, towing light and all-round lights 3 miles.',
    source: 'Rule 22(a)',
  },
  {
    id: 'R36',
    q: 'Which signal should you avoid when trying to attract the attention of another vessel?',
    options: [
      'High-intensity intermittent or revolving lights, such as strobe lights',
      'Directing a searchlight beam in the direction of the danger',
      'A light or sound signal that cannot be mistaken for any signal in the Rules',
      'Calling her on VHF',
    ],
    why: 'Rule 36: you may make light or sound signals that cannot be mistaken for any signal authorized elsewhere in the Rules, or direct a searchlight beam in the direction of the danger. Any light to attract attention shall be such that it cannot be mistaken for an aid to navigation; high-intensity intermittent or revolving lights, such as strobe lights, shall be avoided.',
    source: 'Rule 36',
  },
  // ---- Added 8 Oct 2026 – waiting for Robin's review ----
  {
    id: 'R3a',
    q: 'Under Rule 3(a), the word "vessel" includes:',
    options: [
      'Every description of water craft, including non-displacement craft, WIG craft and seaplanes',
      'Only ships over 20 metres',
      'Only power-driven and sailing vessels',
      'Everything except seaplanes',
    ],
    why: 'Rule 3(a): the word "vessel" includes every description of water craft, including non-displacement craft, WIG craft and seaplanes, used or capable of being used as a means of transportation on water.',
    source: 'Rule 3(a)',
  },
  {
    id: 'R3f',
    q: 'A vessel "not under command" is a vessel that:',
    options: [
      'Through some exceptional circumstance is unable to manoeuvre as required by the Rules',
      'Has no master on board',
      'Is restricted by the nature of her work',
      'Is at anchor without a watch',
    ],
    why: 'Rule 3(f): a vessel which through some exceptional circumstance is unable to manoeuvre as required by these Rules and is therefore unable to keep out of the way of another vessel.',
    source: 'Rule 3(f)',
  },
  {
    id: 'R3g',
    q: 'Which vessel is NOT listed in Rule 3(g) as restricted in her ability to manoeuvre?',
    options: [
      'A vessel engaged in trawling',
      'A vessel laying a submarine cable',
      'A vessel engaged in replenishment underway',
      'A vessel launching or recovering aircraft',
    ],
    why: 'Rule 3(g) lists for example: servicing navigation marks, cables or pipelines; dredging, surveying or underwater operations; replenishment or transferring persons, provisions or cargo underway; launching or recovering aircraft; mine clearance; and towing operations that severely restrict her ability to deviate. A trawler is a vessel engaged in fishing, not RAM.',
    source: 'Rule 3(g)',
  },
  {
    id: 'R7b',
    q: 'Rule 7(b) – proper use of radar – includes:',
    options: [
      'Long-range scanning to obtain early warning of risk of collision, and radar plotting or equivalent systematic observation',
      'Using only the shortest range scale',
      'Switching the radar off in clear weather',
      'Relying on AIS instead of radar',
    ],
    why: 'Rule 7(b): proper use shall be made of radar equipment if fitted and operational, including long-range scanning to obtain early warning of risk of collision and radar plotting or equivalent systematic observation of detected objects.',
    source: 'Rule 7(b)',
  },
  {
    id: 'R9c',
    q: 'In a narrow channel, a vessel engaged in fishing:',
    options: [
      'Shall not impede the passage of any other vessel navigating within the channel',
      'Has right of way over all other vessels in the channel',
      'May anchor in the middle of the channel',
      'Must leave the channel at night',
    ],
    why: 'Rule 9(c): a vessel engaged in fishing shall not impede the passage of any other vessel navigating within a narrow channel or fairway.',
    source: 'Rule 9(c)',
  },
  {
    id: 'R9g',
    q: 'What does Rule 9 say about anchoring in a narrow channel?',
    options: [
      'Any vessel shall, if the circumstances admit, avoid anchoring in a narrow channel',
      'Anchoring is allowed anywhere in the channel',
      'Only vessels under 20 m may anchor there',
      'Anchoring is allowed if you show two anchor lights',
    ],
    why: 'Rule 9(g): any vessel shall, if the circumstances of the case admit, avoid anchoring in a narrow channel.',
    source: 'Rule 9(g)',
  },
  {
    id: 'R10d',
    q: 'Which vessels may use an inshore traffic zone even though they could safely use the traffic lane?',
    options: [
      'Vessels under 20 m, sailing vessels and vessels engaged in fishing',
      'All vessels over 50 m',
      'Only tankers',
      'Any vessel that wants to save time',
    ],
    why: 'Rule 10(d)(i): a vessel shall not use an inshore traffic zone when she can safely use the appropriate traffic lane. However, vessels of less than 20 m, sailing vessels and vessels engaged in fishing may use it. (10(d)(ii) also allows vessels going to or from a port, installation or pilot station inside the zone.)',
    source: 'Rule 10(d)',
  },
  {
    id: 'R10k',
    q: 'A vessel restricted in her ability to manoeuvre while maintaining safety of navigation in a traffic separation scheme:',
    options: [
      'Is exempted from complying with Rule 10 to the extent necessary for the operation',
      'Must still follow the traffic lane exactly',
      'Must leave the scheme before starting work',
      'Becomes the give-way vessel to all others',
    ],
    why: 'Rule 10(k): a vessel restricted in her ability to manoeuvre when engaged in an operation for the maintenance of safety of navigation in a TSS is exempted from complying with this Rule to the extent necessary to carry out the operation. 10(l) gives the same for laying, servicing or picking up a submarine cable.',
    source: 'Rule 10(k)',
  },
  {
    id: 'R18c',
    q: 'A vessel engaged in fishing, underway, shall so far as possible keep out of the way of:',
    options: [
      'A vessel not under command and a vessel restricted in her ability to manoeuvre',
      'A sailing vessel',
      'A power-driven vessel',
      'All other vessels',
    ],
    why: 'Rule 18(c): a vessel engaged in fishing when underway shall, so far as possible, keep out of the way of (i) a vessel not under command and (ii) a vessel restricted in her ability to manoeuvre.',
    source: 'Rule 18(c)',
  },
  {
    id: 'R18f',
    q: 'A WIG craft taking off, landing or in flight near the surface shall:',
    options: [
      'Keep well clear of all other vessels and avoid impeding their navigation',
      'Be treated as the stand-on vessel',
      'Follow the rules for sailing vessels',
      'Always pass ahead of other vessels',
    ],
    why: 'Rule 18(f)(i): a WIG craft when taking off, landing and in flight near the surface shall keep well clear of all other vessels and avoid impeding their navigation. On the water surface she complies with the Rules as a power-driven vessel.',
    source: 'Rule 18(f)',
  },
  // ---- Added 9 Oct 2026 (NEW 9 OCT) – waiting for Robin's review ----
  {
    id: 'R1a',
    q: 'Under Rule 1(a), the Rules apply to:',
    options: [
      'All vessels upon the high seas and in all waters connected therewith navigable by seagoing vessels',
      'Only vessels of 20 m or more on international voyages',
      'Only merchant ships outside territorial waters',
      'Only vessels in traffic separation schemes',
    ],
    why: 'Rule 1(a): these Rules shall apply to all vessels upon the high seas and in all waters connected therewith navigable by seagoing vessels.',
    source: 'Rule 1(a)',
  },
  {
    id: 'R1c',
    q: 'A government allows extra station or signal lights for warships sailing in convoy (Rule 1(c)). These lights shall, so far as possible:',
    options: [
      'Be such that they cannot be mistaken for any light, shape or signal authorised elsewhere in the Rules',
      'Be red, so that other vessels keep clear',
      'Replace the ordinary navigation lights',
      'Only be shown in restricted visibility',
    ],
    why: 'Rule 1(c): these additional station or signal lights, shapes or whistle signals shall, so far as possible, be such that they cannot be mistaken for any light, shape or signal authorised elsewhere under these Rules.',
    source: 'Rule 1(c)',
  },
  {
    id: 'R1d',
    q: 'For the purpose of the Rules, traffic separation schemes are adopted by:',
    options: ['The International Maritime Organization (IMO)', 'Each port authority', 'IALA', 'The flag state of each vessel'],
    why: 'Rule 1(d): traffic separation schemes may be adopted by the Organization (IMO) for the purpose of these Rules.',
    source: 'Rule 1(d)',
  },
  {
    id: 'R1e',
    q: 'A vessel of special construction cannot fully comply with the Rules on the number and position of her lights. Under Rule 1(e) she shall:',
    options: [
      'Comply with other provisions that her government has determined to be the closest possible compliance',
      'Show no navigation lights at all',
      'Show the lights of a vessel not under command',
      'Only navigate by day',
    ],
    why: 'Rule 1(e): such a vessel shall comply with such other provisions in regard to lights, shapes and sound-signalling appliances as her government shall have determined to be the closest possible compliance with these Rules.',
    source: 'Rule 1(e)',
  },
  {
    id: 'R3b',
    q: 'Under Rule 3(b), the term "power-driven vessel" means:',
    options: [
      'Any vessel propelled by machinery',
      'Any vessel that carries an engine, whether it is used or not',
      'Any vessel of 12 m or more with an engine',
      'Any vessel able to make more than 7 knots',
    ],
    why: 'Rule 3(b): the term "power-driven vessel" means any vessel propelled by machinery. A sailing vessel with her engine running ahead is therefore a power-driven vessel.',
    source: 'Rule 3(b)',
  },
  {
    id: 'R3e',
    q: 'Under Rule 3(e), the word "seaplane" includes:',
    options: [
      'Any aircraft designed to manoeuvre on the water',
      'Only aircraft that have landed in a harbour',
      'Any aircraft flying below 500 feet',
      'Helicopters used for pilot transfer',
    ],
    why: 'Rule 3(e): the word "seaplane" includes any aircraft designed to manoeuvre on the water.',
    source: 'Rule 3(e)',
  },
  {
    id: 'R3j',
    q: 'In the Rules, the "length" of a vessel means:',
    options: ['Her length overall', 'Her length between perpendiculars', 'Her length on the waterline', 'Her registered length'],
    why: 'Rule 3(j): the words "length" and "breadth" of a vessel mean her length overall and greatest breadth.',
    source: 'Rule 3(j)',
  },
  {
    id: 'R6a',
    q: 'Which of these is NOT listed in Rule 6(a) as a factor when deciding a safe speed?',
    options: [
      'The vessel\'s scheduled time of arrival',
      'The state of visibility',
      'The traffic density, including concentrations of fishing vessels',
      'The draught in relation to the available depth of water',
    ],
    why: 'Rule 6(a) lists visibility, traffic density, manoeuvrability (stopping distance and turning ability), background light at night, wind, sea and current and the proximity of hazards, and draught in relation to depth. The schedule is not a factor.',
    source: 'Rule 6(a)',
  },
  {
    id: 'R7a',
    q: 'You are not sure whether risk of collision exists. Under Rule 7(a):',
    options: [
      'Such risk shall be deemed to exist',
      'You may assume there is no risk until the other vessel signals',
      'You shall call the other vessel on VHF before deciding',
      'Risk only exists if the other vessel is on your starboard side',
    ],
    why: 'Rule 7(a): every vessel shall use all available means appropriate to the circumstances to determine if risk of collision exists. If there is any doubt such risk shall be deemed to exist.',
    source: 'Rule 7(a)',
  },
  {
    id: 'R7d2',
    q: 'The compass bearing of an approaching vessel is changing appreciably. When may risk of collision still exist?',
    options: [
      'When approaching a very large vessel, a tow, or a vessel at close range',
      'Never – a changing bearing always means no risk',
      'Only in restricted visibility',
      'Only when the other vessel is a sailing vessel',
    ],
    why: 'Rule 7(d)(ii): such risk may sometimes exist even when an appreciable bearing change is evident, particularly when approaching a very large vessel or a tow or when approaching a vessel at close range.',
    source: 'Rule 7(d)(ii)',
  },
  {
    id: 'R8c',
    q: 'If there is sufficient sea room, which action may be the most effective to avoid a close-quarters situation?',
    options: [
      'Alteration of course alone, if made in good time, substantial and not leading to another close-quarters situation',
      'A small reduction of speed',
      'A succession of small alterations of course',
      'Keeping course and speed and sounding five short blasts',
    ],
    why: 'Rule 8(c): if there is sufficient sea-room, alteration of course alone may be the most effective action to avoid a close-quarters situation provided that it is made in good time, is substantial and does not result in another close-quarters situation.',
    source: 'Rule 8(c)',
  },
  {
    id: 'R8d',
    q: 'After you have taken action to avoid collision, Rule 8(d) requires you to:',
    options: [
      'Check the effectiveness of the action until the other vessel is finally past and clear',
      'Return to your original course at once',
      'Report the action to the nearest VTS',
      'Sound one prolonged blast',
    ],
    why: 'Rule 8(d): action taken to avoid collision shall result in passing at a safe distance. The effectiveness of the action shall be carefully checked until the other vessel is finally past and clear.',
    source: 'Rule 8(d)',
  },
  {
    id: 'R8f3',
    q: 'A vessel whose passage must "not be impeded" is approaching another vessel so that risk of collision exists. Under Rule 8(f)(iii) she:',
    options: [
      'Remains fully obliged to comply with the steering and sailing rules',
      'Is always the stand-on vessel and must keep her course and speed',
      'Has no further obligations under the Rules',
      'Must stop her engines',
    ],
    why: 'Rule 8(f)(iii): a vessel the passage of which is not to be impeded remains fully obliged to comply with the Rules of Part B when the two vessels are approaching one another so as to involve risk of collision.',
    source: 'Rule 8(f)(iii)',
  },
  {
    id: 'R9e',
    q: 'In a narrow channel you can only overtake if the vessel ahead takes action to let you pass. What do you do?',
    options: [
      'Indicate your intention with the sound signal in Rule 34(c)(i) and wait for her agreement',
      'Overtake at once – she must keep out of your way',
      'Sound one prolonged blast and pass on either side',
      'Sound five short and rapid blasts',
    ],
    why: 'Rule 9(e)(i): the vessel intending to overtake shall indicate her intention by sounding the signal in Rule 34(c)(i). The vessel to be overtaken shall, if in agreement, sound the signal in Rule 34(c)(ii) and take steps to permit safe passing. If in doubt she may sound the signal in Rule 34(d).',
    source: 'Rule 9(e)(i)',
  },
  {
    id: 'R9e2',
    q: 'The vessel ahead in a narrow channel has agreed to let you overtake. Who is responsible for keeping clear?',
    options: [
      'You are – Rule 9(e) does not relieve the overtaking vessel of her obligation under Rule 13',
      'The vessel being overtaken, since she agreed',
      'Both vessels equally',
      'Neither – the agreement replaces the Rules',
    ],
    why: 'Rule 9(e)(ii): this Rule does not relieve the overtaking vessel of her obligation under Rule 13.',
    source: 'Rule 9(e)(ii)',
  },
  {
    id: 'R10a',
    q: 'Does Rule 10 (traffic separation schemes) relieve a vessel of her obligations under the other Rules?',
    options: [
      'No – Rule 10 does not relieve any vessel of her obligation under any other rule',
      'Yes – a vessel following a lane is always the stand-on vessel',
      'Yes – inside a TSS only Rule 10 applies',
      'Only for vessels of 50 m or more',
    ],
    why: 'Rule 10(a): this Rule applies to traffic separation schemes adopted by the Organization and does not relieve any vessel of her obligation under any other rule.',
    source: 'Rule 10(a)',
  },
  {
    id: 'R10b3',
    q: 'When joining or leaving a traffic lane from the side, you shall do so:',
    options: [
      'At as small an angle to the general direction of traffic flow as practicable',
      'At right angles to the lane',
      'Only at the end of the lane, never from the side',
      'At an angle of 45 degrees',
    ],
    why: 'Rule 10(b)(iii): normally join or leave a traffic lane at the termination of the lane, but when joining or leaving from either side do so at as small an angle to the general direction of traffic flow as practicable.',
    source: 'Rule 10(b)(iii)',
  },
  {
    id: 'R10e',
    q: 'Apart from crossing, joining or leaving a lane, when may a vessel enter a separation zone?',
    options: [
      'In an emergency to avoid immediate danger, or to engage in fishing within the separation zone',
      'Whenever the lane is busy',
      'To anchor while waiting for a pilot',
      'Never, under any circumstances',
    ],
    why: 'Rule 10(e): a vessel other than a crossing vessel or a vessel joining or leaving a lane shall not normally enter a separation zone or cross a separation line except (i) in cases of emergency to avoid immediate danger, (ii) to engage in fishing within a separation zone.',
    source: 'Rule 10(e)',
  },
  {
    id: 'R10f',
    q: 'What does Rule 10 say about navigating near the terminations of a traffic separation scheme?',
    options: [
      'Do so with particular caution',
      'Vessels leaving the scheme have right of way',
      'Speed shall be reduced to 10 knots',
      'Rule 10 does not apply there',
    ],
    why: 'Rule 10(f): a vessel navigating in areas near the terminations of traffic separation schemes shall do so with particular caution.',
    source: 'Rule 10(f)',
  },
  {
    id: 'R10g',
    q: 'What does Rule 10 say about anchoring in a traffic separation scheme?',
    options: [
      'So far as practicable avoid anchoring in the scheme or near its terminations',
      'Anchoring is allowed in the separation zone only',
      'Anchoring is allowed anywhere if anchor lights are shown',
      'Rule 10 says nothing about anchoring',
    ],
    why: 'Rule 10(g): a vessel shall so far as practicable avoid anchoring in a traffic separation scheme or in areas near its terminations.',
    source: 'Rule 10(g)',
  },
  {
    id: 'R10j',
    q: 'In a traffic separation scheme, a vessel of less than 20 m or a sailing vessel:',
    options: [
      'Shall not impede the safe passage of a power-driven vessel following a traffic lane',
      'Has right of way over all power-driven vessels',
      'May not enter the scheme at all',
      'Must use the separation zone',
    ],
    why: 'Rule 10(j): a vessel of less than 20 metres in length or a sailing vessel shall not impede the safe passage of a power-driven vessel following a traffic lane.',
    source: 'Rule 10(j)',
  },
  {
    id: 'R11',
    q: 'Rules 11–18 (conduct of vessels in sight of one another) apply:',
    options: [
      'Only to vessels in sight of one another',
      'In any condition of visibility',
      'Only in restricted visibility',
      'Only in narrow channels and traffic separation schemes',
    ],
    why: 'Rule 11: the Rules in Section II apply to vessels in sight of one another. In restricted visibility, when vessels are not in sight of one another, Rule 19 applies instead.',
    source: 'Rule 11',
  },
  {
    id: 'R14day',
    q: 'By day, how do you know you are in a head-on situation?',
    options: [
      'You see the other vessel ahead or nearly ahead with her masts in line or nearly in line',
      'You see her whole port side',
      'She shows a black ball',
      'Her bearing is changing quickly',
    ],
    why: 'Rule 14(b): such a situation shall be deemed to exist when a vessel sees the other ahead or nearly ahead, and by night she could see the masthead lights in a line or nearly in a line and/or both sidelights, and by day she observes the corresponding aspect of the other vessel.',
    source: 'Rule 14(b)',
  },
  {
    id: 'R15b',
    q: 'In a crossing situation, the give-way power-driven vessel shall, if the circumstances admit, avoid:',
    options: ['Crossing ahead of the other vessel', 'Reducing speed', 'Altering course to starboard', 'Passing astern of the other vessel'],
    why: 'Rule 15: the vessel which has the other on her own starboard side shall keep out of the way and shall, if the circumstances of the case admit, avoid crossing ahead of the other vessel.',
    source: 'Rule 15',
  },
  {
    id: 'R17d',
    q: 'The stand-on vessel has taken action under Rule 17. Does this change the duty of the give-way vessel?',
    options: [
      'No – Rule 17 does not relieve the give-way vessel of her obligation to keep out of the way',
      'Yes – the give-way vessel may now keep her course',
      'Yes – both vessels become stand-on vessels',
      'Only if the stand-on vessel has sounded a signal',
    ],
    why: 'Rule 17(d): this Rule does not relieve the give-way vessel of her obligation to keep out of the way.',
    source: 'Rule 17(d)',
  },
  {
    id: 'R18d2',
    q: 'How shall a vessel constrained by her draught navigate?',
    options: [
      'With particular caution, having full regard to her special condition',
      'At full speed, so as to leave the channel quickly',
      'As a stand-on vessel in all situations',
      'Only with a pilot on board',
    ],
    why: 'Rule 18(d)(ii): a vessel constrained by her draught shall navigate with particular caution having full regard to her special condition.',
    source: 'Rule 18(d)(ii)',
  },
  {
    id: 'R18e',
    q: 'A seaplane on the water shall in general:',
    options: [
      'Keep well clear of all vessels and avoid impeding their navigation',
      'Be treated as a vessel restricted in her ability to manoeuvre',
      'Have right of way over all vessels',
      'Follow the rules for sailing vessels',
    ],
    why: 'Rule 18(e): a seaplane on the water shall, in general, keep well clear of all vessels and avoid impeding their navigation. Where risk of collision exists, she shall comply with the Rules of Part B.',
    source: 'Rule 18(e)',
  },
  {
    id: 'R19c',
    q: 'In restricted visibility, how do Rules 4–10 (any condition of visibility) apply?',
    options: [
      'Every vessel shall have due regard to the prevailing circumstances and conditions of restricted visibility when complying with them',
      'They do not apply – only Rule 19 applies',
      'They only apply to vessels without radar',
      'They only apply to vessels in sight of one another',
    ],
    why: 'Rule 19(c): every vessel shall have due regard to the prevailing circumstances and conditions of restricted visibility when complying with the Rules of Section I of this Part.',
    source: 'Rule 19(c)',
  },
  {
    id: 'R19d2',
    q: 'Restricted visibility: a vessel detected by radar alone is closing from abaft your beam. Which action should you avoid?',
    options: [
      'An alteration of course towards her',
      'An alteration of course away from her',
      'Keeping a systematic radar plot',
      'Sounding the prescribed fog signal',
    ],
    why: 'Rule 19(d)(ii): so far as possible avoid an alteration of course towards a vessel abeam or abaft the beam.',
    source: 'Rule 19(d)(ii)',
  },
  {
    id: 'R20a',
    q: 'The Rules on lights and shapes (Part C) shall be complied with:',
    options: ['In all weathers', 'Only in good visibility', 'Only at night', 'Only outside harbours'],
    why: 'Rule 20(a): Rules in this Part shall be complied with in all weathers.',
    source: 'Rule 20(a)',
  },
  {
    id: 'R20b2',
    q: 'At night, may a vessel show other lights than those prescribed by the Rules?',
    options: [
      'Only lights that cannot be mistaken for the prescribed lights, do not impair their visibility or character, and do not interfere with a proper look-out',
      'Yes, any lights at all',
      'No, never – not even deck lights',
      'Only coloured lights',
    ],
    why: 'Rule 20(b): from sunset to sunrise no other lights shall be exhibited, except such lights as cannot be mistaken for the lights specified in these Rules or do not impair their visibility or distinctive character, or interfere with the keeping of a proper look-out.',
    source: 'Rule 20(b)',
  },
  {
    id: 'R20c',
    q: 'Shall navigation lights be shown by day?',
    options: [
      'Yes, in restricted visibility – and they may be shown in all other circumstances when deemed necessary',
      'No, never by day',
      'Only in harbour',
      'Only by vessels of 50 m or more',
    ],
    why: 'Rule 20(c): the lights prescribed by these Rules shall, if carried, also be exhibited from sunrise to sunset in restricted visibility and may be exhibited in all other circumstances when it is deemed necessary.',
    source: 'Rule 20(c)',
  },
  {
    id: 'R20d',
    q: 'When shall the shapes in the Rules be shown?',
    options: ['By day', 'By night', 'Only in restricted visibility', 'Only in harbour'],
    why: 'Rule 20(d): the Rules concerning shapes shall be complied with by day.',
    source: 'Rule 20(d)',
  },
  {
    id: 'R22mast20',
    q: 'What is the minimum range of the masthead light of a vessel of 20 m or more but less than 50 m?',
    options: ['5 miles', '3 miles', '6 miles', '2 miles'],
    why: 'Rule 22(b): in vessels of 12 m or more but less than 50 m, the masthead light shall be visible 5 miles – except that where the length of the vessel is less than 20 m, 3 miles.',
    source: 'Rule 22(b)',
  },
  {
    id: 'R22stern',
    q: 'What is the minimum range of the sternlight of a vessel of 50 m or more?',
    options: ['3 miles', '2 miles', '6 miles', '5 miles'],
    why: 'Rule 22(a): in vessels of 50 m or more – masthead light 6 miles, sidelight 3 miles, sternlight 3 miles, towing light 3 miles, all-round light 3 miles.',
    source: 'Rule 22(a)',
  },
  {
    id: 'R22side12',
    q: 'What is the minimum range of the sidelights of a vessel of less than 12 m?',
    options: ['1 mile', '2 miles', '3 miles', 'Half a mile'],
    why: 'Rule 22(c): in vessels of less than 12 m – masthead light 2 miles, sidelight 1 mile, sternlight 2 miles, towing light 2 miles, all-round light 2 miles.',
    source: 'Rule 22(c)',
  },
  {
    id: 'R22round',
    q: 'What is the minimum range of an all-round white, red, green or yellow light on a vessel of 50 m or more?',
    options: ['3 miles', '2 miles', '6 miles', '5 miles'],
    why: 'Rule 22(a): in vessels of 50 m or more, a white, red, green or yellow all-round light shall be visible at least 3 miles.',
    source: 'Rule 22(a)',
  },
  {
    id: 'R31',
    q: 'A seaplane or WIG craft cannot show lights and shapes exactly as prescribed. Under Rule 31 she shall:',
    options: [
      'Show lights and shapes as closely similar in characteristics and position as possible',
      'Show no lights at all',
      'Show the lights of a vessel not under command',
      'Only operate by day',
    ],
    why: 'Rule 31: where it is impracticable for a seaplane or a WIG craft to exhibit lights and shapes of the characteristics or in the positions prescribed, she shall exhibit lights and shapes as closely similar in characteristics and position as is possible.',
    source: 'Rule 31',
  },
  {
    id: 'A1h1',
    q: 'On a power-driven vessel of 20 m or more, the forward masthead light shall be placed at a height above the hull of not less than:',
    options: [
      '6 m – or the breadth of the vessel if greater – but it need not be higher than 12 m',
      '2.5 m above the gunwale',
      '4.5 m',
      'Half the length of the vessel',
    ],
    why: 'Annex I 2(a)(i): not less than 6 metres, and if the breadth of the vessel exceeds 6 metres, then not less than such breadth, so however that the light need not be placed at a greater height above the hull than 12 metres.',
    source: 'COLREG Annex I 2(a)(i)',
  },
  {
    id: 'A1h2',
    q: 'When two masthead lights are carried, how much higher than the forward one shall the after one be?',
    options: ['At least 4.5 m vertically higher', 'At least 1 m higher', 'At least 2 m higher', 'At the same height'],
    why: 'Annex I 2(a)(ii): when two masthead lights are carried the after one shall be at least 4.5 metres vertically higher than the forward one.',
    source: 'COLREG Annex I 2(a)(ii)',
  },
  {
    id: 'A1h3',
    q: 'The masthead light of a power-driven vessel of 12 m or more but less than 20 m shall be at least how high above the gunwale?',
    options: ['2.5 m', '1 m', '4.5 m', '6 m'],
    why: 'Annex I 2(c): the masthead light of a power-driven vessel of 12 metres but less than 20 metres in length shall be placed at a height above the gunwale of not less than 2.5 metres.',
    source: 'COLREG Annex I 2(c)',
  },
  {
    id: 'A1hz',
    q: 'What is the minimum horizontal distance between the two masthead lights of a power-driven vessel?',
    options: [
      'Half the length of the vessel, but it need not be more than 100 m',
      'A quarter of the length of the vessel',
      '10 m',
      'The breadth of the vessel',
    ],
    why: 'Annex I 3(a): the horizontal distance between them shall not be less than one-half of the length of the vessel but need not be more than 100 metres. The forward light shall be not more than one-quarter of the length from the stem.',
    source: 'COLREG Annex I 3(a)',
  },
  {
    id: 'A1ball',
    q: 'What is the minimum diameter of a ball shape?',
    options: ['0.6 m', '0.3 m', '1 m', '1.5 m'],
    why: 'Annex I 6(a)(i): a ball shall have a diameter of not less than 0.6 metre. Smaller shapes may be used on vessels of less than 20 m.',
    source: 'COLREG Annex I 6(a)',
  },
  {
    id: 'A1cyl',
    q: 'A cylinder shape (vessel constrained by her draught) shall have a height of:',
    options: ['Twice its diameter', 'Equal to its diameter', 'Half its diameter', '1.5 m regardless of diameter'],
    why: 'Annex I 6(a)(iii): a cylinder shall have a diameter of at least 0.6 metre and a height of twice its diameter. A cone has a height equal to its base diameter.',
    source: 'COLREG Annex I 6(a)',
  },
  {
    id: 'A1gap',
    q: 'What is the minimum vertical distance between shapes?',
    options: ['1.5 m', '0.6 m', '1 m', '2 m'],
    why: 'Annex I 6(b): the vertical distance between shapes shall be at least 1.5 metre. Vessels of less than 20 m may use smaller shapes and reduce the distance accordingly.',
    source: 'COLREG Annex I 6(b)',
  },
  {
    id: 'A2shoot',
    q: 'Annex II: a trawler fishing close to other fishing vessels shows two white lights in a vertical line. What is she doing?',
    options: ['Shooting her nets', 'Hauling her nets', 'Her net has come fast upon an obstruction', 'She is at anchor'],
    why: 'Annex II 2(a): vessels of 20 m or more engaged in trawling show (i) when shooting their nets: two white lights in a vertical line; (ii) when hauling: one white light over one red light; (iii) when the net has come fast upon an obstruction: two red lights.',
    source: 'COLREG Annex II 2(a)',
  },
  {
    id: 'A2haul',
    q: 'Annex II: a trawler shows one white light over one red light in a vertical line, in addition to her trawling lights. What is she doing?',
    options: ['Hauling her nets', 'Shooting her nets', 'Her net has come fast upon an obstruction', 'Pair trawling'],
    why: 'Annex II 2(a)(ii): when hauling their nets, one white light over one red light in a vertical line.',
    source: 'COLREG Annex II 2(a)',
  },
  {
    id: 'A2fast',
    q: 'Annex II: a trawler shows two red lights in a vertical line, in addition to her trawling lights. What does it mean?',
    options: ['Her net has come fast upon an obstruction', 'She is hauling her nets', 'She is shooting her nets', 'She is pair trawling'],
    why: 'Annex II 2(a)(iii): when the net has come fast upon an obstruction, two red lights in a vertical line.',
    source: 'COLREG Annex II 2(a)',
  },
  {
    id: 'A2pair',
    q: 'Annex II: by night, each vessel of 20 m or more engaged in pair trawling shall direct:',
    options: [
      'A searchlight forward and in the direction of the other vessel of the pair',
      'A searchlight towards any approaching vessel',
      'A searchlight onto the net',
      'A flashing yellow light astern',
    ],
    why: 'Annex II 2(b)(i): each vessel engaged in pair trawling shall exhibit by night a searchlight directed forward and in the direction of the other vessel of the pair.',
    source: 'COLREG Annex II 2(b)',
  },
  {
    id: 'A2purse',
    q: 'Annex II: a purse seiner hampered by her fishing gear may show:',
    options: [
      'Two yellow lights in a vertical line, flashing alternately every second',
      'Two red lights in a vertical line',
      'One all-round flashing yellow light',
      'Three white lights in a vertical line',
    ],
    why: 'Annex II 3: vessels engaged in fishing with purse seine gear may exhibit two yellow lights in a vertical line, flashing alternately every second with equal light and occultation duration – only when the vessel is hampered by her fishing gear.',
    source: 'COLREG Annex II 3',
  },
]
