import type { TheoryItem } from '../study/generators/theory'

// Distress and GMDSS basics. The first option is the correct one.
// Added 8 Oct 2026 – waiting for Robin's review.

export const DISTRESS_THEORY: (TheoryItem & { id: string })[] = [
  {
    id: 'D1',
    q: 'Under Annex IV, the use of a distress signal for any other purpose than indicating distress and need of assistance is:',
    options: ['Prohibited', 'Allowed for training at sea', 'Allowed if you call the coast station first', 'Allowed in harbour'],
    why: 'Annex IV 2: the use or exhibition of any of the foregoing signals except for the purpose of indicating distress and need of assistance and the use of other signals which may be confused with them is prohibited.',
    source: 'COLREG Annex IV 2',
  },
  {
    id: 'D2',
    q: 'A piece of orange canvas with a black square and circle is used:',
    options: ['For identification from the air', 'To mark a wreck', 'As a quarantine signal', 'To show that a diver is down'],
    why: 'Annex IV 3(a): a piece of orange-coloured canvas with either a black square and circle or other appropriate symbol, for identification from the air.',
    source: 'COLREG Annex IV 3',
  },
  {
    id: 'D3',
    q: 'Which word starts a spoken distress call on the radio?',
    options: ['MAYDAY', 'PAN-PAN', 'SÉCURITÉ', 'SOS'],
    why: 'A distress call starts with MAYDAY spoken three times. PAN-PAN is the urgency signal and SÉCURITÉ the safety signal. Annex IV 1(e): the spoken word MAYDAY by radiotelephony.',
    source: 'COLREG Annex IV, Radio Regulations',
  },
  {
    id: 'D4',
    q: 'Which signal is used for an urgent message that is NOT distress, for example a person seriously ill on board?',
    options: ['PAN-PAN', 'MAYDAY', 'SÉCURITÉ', 'SEELONCE'],
    why: 'PAN-PAN (spoken three times) is the urgency signal: a very urgent message about the safety of a ship, aircraft or person, but no grave and imminent danger.',
    source: 'Radio Regulations',
  },
  {
    id: 'D5',
    q: 'On which VHF channel is a DSC distress alert sent?',
    options: ['Channel 70', 'Channel 16', 'Channel 13', 'Channel 6'],
    why: 'VHF DSC uses channel 70. The voice distress traffic that follows is on channel 16.',
    source: 'GMDSS',
  },
  {
    id: 'D6',
    q: 'On which MF frequency is a DSC distress alert sent?',
    options: ['2187.5 kHz', '2182 kHz', '518 kHz', '8414.5 kHz'],
    why: 'MF DSC distress alerting is on 2187.5 kHz; the voice distress traffic follows on 2182 kHz. 518 kHz is NAVTEX.',
    source: 'GMDSS',
  },
  {
    id: 'D7',
    q: 'On which frequency does a satellite EPIRB send its distress alert?',
    options: ['406 MHz', '121.5 MHz', '156.8 MHz', '9 GHz'],
    why: 'Cospas-Sarsat EPIRBs transmit on 406 MHz. Many also have a 121.5 MHz homing signal.',
    source: 'GMDSS',
  },
  {
    id: 'D8',
    q: 'How does an activated radar SART appear on a ship\'s X-band radar?',
    options: [
      'As a line of 12 dots outwards from the SART position',
      'As a single bright echo',
      'As a flashing Morse "D"',
      'It does not show on radar',
    ],
    why: 'A radar SART answers 9 GHz (X-band) radar pulses. On the screen it shows as a line of 12 dots extending outwards from its position; the dot closest to own ship marks the SART.',
    source: 'GMDSS',
  },
  {
    id: 'D9',
    q: 'Rule 37 says that a vessel in distress and requiring assistance shall:',
    options: [
      'Use or exhibit the signals described in Annex IV',
      'Only call on VHF channel 16',
      'Fly flag O',
      'Sound five short blasts',
    ],
    why: 'Rule 37: when a vessel is in distress and requires assistance she shall use or exhibit the signals described in Annex IV to these Regulations.',
    source: 'Rule 37',
  },
  // ---- Added 9 Oct 2026 (NEW 9 OCT) – waiting for Robin's review ----
  {
    id: 'D10',
    q: 'The master of a ship at sea receives information that persons are in distress. SOLAS V/33 requires him to:',
    options: [
      'Proceed with all speed to their assistance, if able to do so',
      'Only report it to the flag state',
      'Continue the voyage unless a coast station orders him to assist',
      'Assist only if the persons are of the same nationality',
    ],
    why: 'SOLAS V/33.1: the master of a ship at sea which is in a position to be able to provide assistance, on receiving information from any source that persons are in distress at sea, is bound to proceed with all speed to their assistance, if possible informing them or the SAR service. If he does not, the reason shall be entered in the logbook.',
    source: 'SOLAS V/33',
  },
  {
    id: 'D11',
    q: 'When should you send a MAYDAY RELAY?',
    options: [
      'When the vessel in distress cannot send the alert herself, or her alert has not been acknowledged and you cannot help',
      'Every time you hear a MAYDAY, to make sure it is heard',
      'Only when ordered by the vessel in distress',
      'When your own vessel is in distress',
    ],
    why: 'A MAYDAY RELAY is sent when the vessel in distress is not able to transmit the alert herself, when the master considers further help is needed, or when a distress alert has not been acknowledged and you are not in a position to assist.',
    source: 'Radio Regulations, GMDSS',
  },
  {
    id: 'D12',
    q: 'What does "SEELONCE MAYDAY" mean?',
    options: [
      'Radio silence – only distress traffic may be sent on the channel',
      'Distress traffic is finished',
      'Restricted working may resume',
      'The vessel in distress has sunk',
    ],
    why: 'SEELONCE MAYDAY is used by the vessel in distress or the station controlling the distress traffic to impose silence on stations that interfere.',
    source: 'Radio Regulations',
  },
  {
    id: 'D13',
    q: 'What does "SEELONCE FEENEE" mean?',
    options: [
      'The distress traffic is finished and normal working may resume',
      'Radio silence is imposed',
      'Restricted working may resume while distress traffic continues',
      'Change to another channel',
    ],
    why: 'SEELONCE FEENEE is sent by the station that controlled the distress traffic when it is over: normal working may resume.',
    source: 'Radio Regulations',
  },
  {
    id: 'D14',
    q: 'What does "PRUDONCE" mean during distress traffic?',
    options: [
      'Restricted working may resume, but distress traffic is still in progress',
      'Distress traffic is finished',
      'Total radio silence',
      'Repeat your last message',
    ],
    why: 'PRUDONCE means that restricted working may resume on the frequency, but distress traffic is still going on – listen carefully and keep transmissions short.',
    source: 'Radio Regulations',
  },
  {
    id: 'D15',
    q: 'In a spoken MAYDAY message, what comes directly after the identification of the vessel in distress?',
    options: ['Her position', 'The number of persons on board', 'The weather', 'The name of the master'],
    why: 'Order of a distress message: MAYDAY – this is (name, call sign, MMSI) – position – nature of distress – assistance required – other information, for example persons on board. Position comes first because it is what rescuers need most.',
    source: 'GMDSS / ITU',
  },
  {
    id: 'D16',
    q: 'Which signal starts an important navigational or meteorological warning on the radio?',
    options: ['SÉCURITÉ', 'PAN-PAN', 'MAYDAY', 'SEELONCE'],
    why: 'SÉCURITÉ (spoken three times) is the safety signal, used for important navigational or meteorological warnings.',
    source: 'Radio Regulations',
  },
  {
    id: 'D17',
    q: 'On which frequency is the international NAVTEX service broadcast?',
    options: ['518 kHz', '490 kHz', '2182 kHz', '156.8 MHz'],
    why: 'International NAVTEX is on 518 kHz in English. 490 kHz (and 4209.5 kHz) are used for national NAVTEX broadcasts.',
    source: 'GMDSS',
  },
  {
    id: 'D18',
    q: 'VHF channel 16 is on which frequency?',
    options: ['156.8 MHz', '156.525 MHz', '156.3 MHz', '406 MHz'],
    why: 'Channel 16 (156.8 MHz) is the VHF distress, urgency, safety and calling channel. 156.525 MHz is channel 70 (DSC).',
    source: 'Radio Regulations',
  },
  {
    id: 'D19',
    q: 'Which VHF channel is used for bridge-to-bridge navigation safety communication?',
    options: ['Channel 13', 'Channel 70', 'Channel 6', 'Channel 9'],
    why: 'Channel 13 is used worldwide for navigation safety communication between ships, mainly bridge-to-bridge.',
    source: 'Radio Regulations',
  },
  {
    id: 'D20',
    q: 'Which VHF channel is used for on-scene SAR communication between ships and aircraft?',
    options: ['Channel 6', 'Channel 13', 'Channel 70', 'Channel 12'],
    why: 'Channel 6 (156.3 MHz) may be used for communication between ship stations and aircraft engaged in coordinated search and rescue operations.',
    source: 'Radio Regulations',
  },
  {
    id: 'D21',
    q: 'You receive a VHF DSC distress alert from a vessel that may be near you. What should you normally do first?',
    options: [
      'Listen on channel 16 and, if she is in your area, acknowledge by voice',
      'Immediately send a DSC acknowledgement on channel 70',
      'Relay the alert by DSC to all ships',
      'Reset the radio and ignore it if a coast station is in range',
    ],
    why: 'IMO guidance: a ship receiving a VHF DSC distress alert should set watch on channel 16 and, if the vessel in distress is in the area, acknowledge by radiotelephony. Acknowledgement by DSC is normally left to the coast station.',
    source: 'IMO GMDSS guidance',
  },
  {
    id: 'D22',
    q: 'You send a DSC distress alert by mistake. What do you do?',
    options: [
      'Cancel it by voice to all stations on the associated distress channel (VHF channel 16)',
      'Nothing – the coast station will understand',
      'Switch off the radio',
      'Send a second DSC distress alert',
    ],
    why: 'A false alert shall be cancelled at once: reset the equipment, then make an "All stations" broadcast on the associated voice frequency (VHF ch 16) giving name, call sign, MMSI and position, and cancel the distress alert.',
    source: 'IMO GMDSS guidance',
  },
  {
    id: 'D23',
    q: 'At about what depth does the hydrostatic release of a float-free EPIRB operate?',
    options: ['1.5 to 4 metres', '10 to 15 metres', 'At the surface, when it gets wet', '20 metres'],
    why: 'A hydrostatic release unit frees the EPIRB at a depth of about 1.5 to 4 metres, so it floats up and starts transmitting even if nobody can reach it.',
    source: 'SOLAS / LSA',
  },
  {
    id: 'D24',
    q: 'A 406 MHz satellite EPIRB must be able to transmit for at least:',
    options: ['48 hours', '12 hours', '96 hours', '6 hours'],
    why: 'The battery of a 406 MHz EPIRB shall have capacity to operate the beacon for at least 48 hours.',
    source: 'IMO performance standards',
  },
  {
    id: 'D25',
    q: 'At about what range can a SART be detected by a ship\'s radar with the antenna 15 m above the sea?',
    options: ['About 5 nautical miles', 'About 30 nautical miles', 'About 1 nautical mile', 'About 50 nautical miles'],
    why: 'A radar SART shall be detectable at least 5 nautical miles by a ship\'s radar with the antenna 15 m above sea level, and about 30 nautical miles by an aircraft at 3000 ft.',
    source: 'IMO performance standards',
  },
  {
    id: 'D26',
    q: 'You approach an activated radar SART. Within about 1 nautical mile, how does the line of 12 dots change?',
    options: [
      'The dots become wide arcs, and finally concentric circles',
      'They disappear completely',
      'They become one bright dot',
      'They start flashing in Morse',
    ],
    why: 'Close to the SART the radar picks up the response also through the side lobes, so the dots widen into arcs and finally into concentric circles around the SART position.',
    source: 'GMDSS',
  },
  {
    id: 'D27',
    q: 'How does an AIS-SART appear on the AIS / ECDIS display?',
    options: [
      'As an AIS target marked "SART ACTIVE"',
      'As a line of 12 dots on the X-band radar',
      'As a red flashing area on the chart',
      'It is only shown at the coast station',
    ],
    why: 'An AIS-SART sends AIS messages with its GPS position. It is shown as a special target (circle with a cross) with the text "SART ACTIVE" (or "SART TEST").',
    source: 'GMDSS',
  },
  {
    id: 'D28',
    q: 'GMDSS sea area A1 is the area within range of:',
    options: [
      'At least one VHF coast station with continuous DSC alerting',
      'An MF coast station with DSC',
      'Inmarsat geostationary satellites',
      'NAVTEX transmitters',
    ],
    why: 'A1: within radiotelephone coverage of at least one VHF coast station with continuous DSC alerting. A2: MF coast station. A3: Inmarsat coverage. A4: the rest – the polar areas.',
    source: 'SOLAS IV/2',
  },
  {
    id: 'D29',
    q: 'GMDSS sea area A4 is:',
    options: [
      'An area outside sea areas A1, A2 and A3 – in practice the polar areas',
      'The area within VHF range of a coast station',
      'The area covered by Inmarsat satellites',
      'The area within MF range of a coast station',
    ],
    why: 'A4 is an area outside sea areas A1, A2 and A3. These are essentially the polar regions, north and south of about 70°.',
    source: 'SOLAS IV/2',
  },
  {
    id: 'D30',
    q: 'Which satellite system broadcasts maritime safety information (MSI) outside NAVTEX coverage?',
    options: ['EGC – for example SafetyNET', 'Cospas-Sarsat', 'AIS', 'DGPS'],
    why: 'Enhanced Group Call (EGC) – Inmarsat SafetyNET and, today, also Iridium SafetyCast – broadcasts navigational and meteorological warnings and SAR information by satellite.',
    source: 'GMDSS',
  },
  {
    id: 'D31',
    q: 'A rocket parachute flare shall burn for at least:',
    options: ['40 seconds', '10 seconds', '3 minutes', '1 minute'],
    why: 'LSA Code: a rocket parachute flare shall reach an altitude of not less than 300 m and burn for not less than 40 seconds. A hand flare burns for not less than 1 minute.',
    source: 'LSA Code',
  },
  {
    id: 'D32',
    q: 'A buoyant smoke signal shall give off orange smoke for at least:',
    options: ['3 minutes', '40 seconds', '1 minute', '15 minutes'],
    why: 'LSA Code: a buoyant smoke signal shall emit smoke of a highly visible colour at a uniform rate for a period of not less than 3 minutes when floating in calm water.',
    source: 'LSA Code',
  },
]
