// IALA theory questions. Q1–Q20 were reviewed by Robin (Google Doc "IALA sample questions").
// The first option is the correct one; the app shuffles them.

export interface TheoryQuestion {
  id: string
  q: string
  options: string[]
  why: string
  source: string
}

export const IALA_THEORY: TheoryQuestion[] = [
  {
    id: 'Q1',
    q: "Region A. You are entering harbour from seaward and see a red, can-shaped buoy ahead. How do you pass it?",
    options: ["Keep it on your port side", "Keep it on your starboard side", "Pass on either side", "Keep well clear, it marks a wreck"],
    why: "In Region A, port-hand marks are red and can-shaped. When following the direction of buoyage, keep them on your port side.",
    source: "IALA MBS (R1001), lateral marks, Region A",
  },
  {
    id: 'Q2',
    q: "Region B. You are entering harbour from seaward. What colour are the starboard-hand marks?",
    options: ["Red", "Green", "Yellow", "Black and red"],
    why: "Region B reverses the lateral colours: starboard-hand marks are red and port-hand marks are green (\"red right returning\"). Region B covers the Americas, Japan, the Republic of Korea and the Philippines.",
    source: "IALA MBS (R1001), lateral marks and buoyage regions",
  },
  {
    id: 'Q3',
    q: "What is the topmark of a port-hand lateral mark in Region A?",
    options: ["A single red can (cylinder)", "A single red sphere", "A single green cone, point up", "Two black spheres"],
    why: "Port-hand marks carry a single red cylinder (can). Starboard-hand marks in Region A carry a single green cone, point up.",
    source: "IALA MBS (R1001), lateral marks",
  },
  {
    id: 'Q4',
    q: "Region A. You see a green, conical buoy with one broad red horizontal band and a green cone topmark. What does it mark?",
    options: ["Preferred channel to port", "Preferred channel to starboard", "A wreck", "The start of a traffic separation scheme"],
    why: "This is a modified starboard-hand mark. It shows where a channel divides and that the preferred (main) channel is to port. Keep it on your starboard side to follow the preferred channel.",
    source: "IALA MBS (R1001), preferred channel marks",
  },
  {
    id: 'Q5',
    q: "Which light rhythm is used on preferred channel marks?",
    options: ["Composite group flashing Fl(2+1)", "Fl(2)", "Q(6)+LFl", "Iso 4s"],
    why: "Fl(2+1) is reserved for modified lateral (preferred channel) marks. Normal lateral marks may use any rhythm except this one.",
    source: "IALA MBS (R1001), preferred channel marks",
  },
  {
    id: 'Q6',
    q: "You see a buoy with a topmark of two black cones, both points up. On which side of the buoy is the safe water?",
    options: ["North", "South", "East", "West"],
    why: "Two cones pointing up is a north cardinal mark. The safe water is to the north, so pass north of it.",
    source: "IALA MBS (R1001), cardinal marks",
  },
  {
    id: 'Q7',
    q: "At night you see a white light showing VQ(3) 5s. What is it?",
    options: ["East cardinal mark", "West cardinal mark", "Isolated danger mark", "Safe water mark"],
    why: "East cardinal marks show three very quick (or quick) flashes: VQ(3) 5s or Q(3) 10s.",
    source: "IALA MBS (R1001), cardinal marks",
  },
  {
    id: 'Q8',
    q: "A south cardinal mark shows Q(6)+LFl 15s. Why is the long flash added after the six short flashes?",
    options: ["So the group of six cannot be mistaken for a group of three or nine", "To show that the mark is lit by solar power", "To mark that it is a new danger", "To identify Region B"],
    why: "Short flashes are easy to miscount. The long flash (at least 2 seconds) marks the end of the group, so a south mark is not taken for an east or west mark.",
    source: "IALA MBS (R1001), cardinal marks",
  },
  {
    id: 'Q9',
    q: "What does a west cardinal mark look like?",
    options: ["Yellow with one broad black horizontal band", "Black with one broad yellow horizontal band", "Black above yellow", "Yellow above black"],
    why: "West: yellow with a black band. East: black with a yellow band. North: black above yellow. South: yellow above black. The black parts point to where the cones point.",
    source: "IALA MBS (R1001), cardinal marks",
  },
  {
    id: 'Q10',
    q: "Which memory aid matches the flash counts of the cardinal marks?",
    options: ["A clock face: East 3, South 6, West 9", "Compass points: East 1, South 2, West 3", "Morse letters: E, S, W", "There is no pattern"],
    why: "East shows 3 flashes, South 6 and West 9, like the hours on a clock face. North flashes continuously.",
    source: "IALA MBS (R1001), cardinal marks",
  },
  {
    id: 'Q11',
    q: "What topmark does an isolated danger mark carry?",
    options: ["Two black spheres, one above the other", "A single red sphere", "A yellow X", "Two black cones, base to base"],
    why: "Isolated danger marks carry two black spheres. They are black with one or more broad red horizontal bands.",
    source: "IALA MBS (R1001), isolated danger marks",
  },
  {
    id: 'Q12',
    q: "What light does an isolated danger mark show?",
    options: ["White, Fl(2)", "Red, Fl(2)", "White, Iso", "Yellow, Fl"],
    why: "Group flashing two, white. Think of the two black spheres on top.",
    source: "IALA MBS (R1001), isolated danger marks",
  },
  {
    id: 'Q13',
    q: "What does an isolated danger mark tell you?",
    options: ["A danger of limited extent with navigable water all around it", "Navigable water all around, for example at a landfall", "The edge of a dredged channel", "A special area, such as a spoil ground"],
    why: "It is placed on or above a danger of limited size that has navigable water all around. Do not pass close to it.",
    source: "IALA MBS (R1001), isolated danger marks",
  },
  {
    id: 'Q14',
    q: "You see a buoy with red and white vertical stripes and a single red sphere topmark. What does it mean?",
    options: ["Safe water, with navigable water all around", "Isolated danger", "Preferred channel", "Emergency wreck"],
    why: "This is a safe water mark, used for example as a landfall or mid-channel mark.",
    source: "IALA MBS (R1001), safe water marks",
  },
  {
    id: 'Q15',
    q: "Which of these lights can NOT be used on a safe water mark?",
    options: ["Q(9) 15s", "Iso", "Oc", "Morse \"A\""],
    why: "Safe water marks show a white light that is isophase, occulting, one long flash every 10 seconds or Morse \"A\". Q(9) is a west cardinal mark.",
    source: "IALA MBS (R1001), safe water marks",
  },
  {
    id: 'Q16',
    q: "You see a yellow buoy with a yellow X-shaped topmark. What is it?",
    options: ["A special mark", "A new danger", "A west cardinal mark", "A safe water mark"],
    why: "Special marks are yellow with a yellow X topmark and, if lit, a yellow light. They mark special areas or features, such as a cable, spoil ground or data buoy.",
    source: "IALA MBS (R1001), special marks",
  },
  {
    id: 'Q17',
    q: "What does the Emergency Wreck Marking Buoy look like?",
    options: ["Blue and yellow vertical stripes, a yellow upright cross topmark, and alternating blue and yellow flashes", "Red and white vertical stripes with a red sphere", "Yellow with a yellow X and a yellow light", "Black with red bands and two black spheres"],
    why: "The Emergency Wreck Marking Buoy is used to mark a new wreck quickly. Its light alternates blue and yellow flashes.",
    source: "IALA MBS (R1001), new dangers and the Emergency Wreck Marking Buoy",
  },
  {
    id: 'Q18',
    q: "A new danger is marked with a racon. Which Morse letter does the racon show on your radar?",
    options: ["D", "A", "U", "K"],
    why: "A new danger mark may carry a racon coded Morse \"D\" (\u2013 \u00b7 \u00b7), showing about 1 nautical mile long on the radar display.",
    source: "IALA MBS (R1001), new dangers",
  },
  {
    id: 'Q19',
    q: "When there is no harbour to approach, for example along a coast, how is the general direction of buoyage decided?",
    options: ["By the buoyage authorities, in general clockwise around continental land masses", "Always from north to south", "Always with the flood stream", "The navigator chooses"],
    why: "The general direction is set by the authorities, usually clockwise around land masses. It is shown on charts and in publications.",
    source: "IALA MBS (R1001), direction of buoyage",
  },
  {
    id: 'Q20',
    q: "Region A. At night you see a red light showing Fl(2) R. What is it most likely to be?",
    options: ["A port-hand lateral mark", "An isolated danger mark", "A south cardinal mark", "A special mark"],
    why: "In Region A, red lights are used only on port-hand marks: the normal port-hand mark, and the modified port-hand mark (preferred channel to starboard), which shows Fl(2+1) R. The isolated danger mark also shows Fl(2), but in white.",
    source: "IALA MBS (R1001), lateral marks",
  },
  // ---- Added 8 Oct 2026 – waiting for Robin's review ----
  {
    id: 'Q21',
    q: 'Which light rhythm may NOT be used on an ordinary port- or starboard-hand lateral mark?',
    options: ['Composite group flashing Fl(2+1)', 'Group flashing Fl(3)', 'Quick flashing Q', 'Flashing Fl'],
    why: 'Lateral marks may have any rhythm except composite group flashing (2+1), which is kept for preferred channel marks.',
    source: 'IALA MBS – lateral marks',
  },
  {
    id: 'Q22',
    q: 'Region A. What colour is the light on a port-hand lateral mark?',
    options: ['Red', 'Green', 'White', 'Yellow'],
    why: 'In Region A port-hand marks are red and show a red light; starboard-hand marks are green with a green light. Region B is the other way round.',
    source: 'IALA MBS – lateral marks',
  },
  {
    id: 'Q23',
    q: 'Region A. What is the topmark of a starboard-hand lateral mark?',
    options: ['A single green cone, point up', 'A single green can', 'Two green cones, points up', 'A green sphere'],
    why: 'A starboard-hand mark carries a single green cone, point upward (Region A). A port-hand mark carries a single red can.',
    source: 'IALA MBS – lateral marks',
  },
  {
    id: 'Q24',
    q: 'Region B. You are entering harbour from seaward. What colour are the port-hand marks?',
    options: ['Green', 'Red', 'Yellow', 'Black and red'],
    why: 'In Region B the colours are reversed: port-hand marks are green and starboard-hand marks are red ("red right returning").',
    source: 'IALA MBS – Region B',
  },
  {
    id: 'Q25',
    q: 'Region A. How is a "preferred channel to starboard" marked?',
    options: [
      'A red port-hand mark with one broad green horizontal band',
      'A green starboard-hand mark with one broad red horizontal band',
      'A yellow mark with a green topmark',
      'A red and white vertically striped mark',
    ],
    why: 'Where a channel divides, a modified port-hand mark (red with one broad green band, red can topmark) shows that the preferred channel is to starboard. Its light is Fl(2+1) R.',
    source: 'IALA MBS – preferred channel marks',
  },
  {
    id: 'Q26',
    q: 'Which parts of the world use IALA Region B?',
    options: [
      'North, Central and South America, Japan, the Republic of Korea and the Philippines',
      'Europe, Africa, Australia and most of Asia',
      'Only the United States',
      'All countries south of the equator',
    ],
    why: 'Region B covers the Americas, Japan, the Republic of Korea and the Philippines. The rest of the world uses Region A.',
    source: 'IALA MBS – the two regions',
  },
  {
    id: 'Q27',
    q: 'How do cardinal marks differ between Region A and Region B?',
    options: ['They are the same in both regions', 'The colours are reversed', 'The topmarks are reversed', 'Region B uses red lights on cardinal marks'],
    why: 'Only the colours of lateral marks differ between the regions. Cardinal, isolated danger, safe water and special marks are the same everywhere.',
    source: 'IALA MBS',
  },
  {
    id: 'Q28',
    q: 'What colours is a north cardinal mark?',
    options: ['Black above yellow', 'Yellow above black', 'Black with one broad yellow band', 'Yellow with one broad black band'],
    why: 'The topmark cones point to where the black is: north – both up, so black is at the top. South is yellow above black, east is black with a yellow band, west is yellow with a black band.',
    source: 'IALA MBS – cardinal marks',
  },
  {
    id: 'Q29',
    q: 'What colours is an east cardinal mark?',
    options: ['Black with one broad horizontal yellow band', 'Yellow with one broad horizontal black band', 'Black above yellow', 'Yellow above black'],
    why: 'East: cones base to base, so they point up and down. The black is where the points are – at the top and bottom – with a yellow band between.',
    source: 'IALA MBS – cardinal marks',
  },
  {
    id: 'Q30',
    q: 'What is the topmark of a south cardinal mark?',
    options: ['Two black cones, both points down', 'Two black cones, both points up', 'Two black cones, base to base', 'Two black cones, point to point'],
    why: 'South: both cones point down (to the south). North: both up. East: base to base. West: point to point.',
    source: 'IALA MBS – cardinal marks',
  },
  {
    id: 'Q31',
    q: 'By day, what is the most important feature of a cardinal mark?',
    options: ['The black double-cone topmark', 'The shape of the buoy', 'The number painted on it', 'The height of the mark'],
    why: 'IALA describes the double-cone topmark as the most important feature of every cardinal mark by day. The buoy itself is a pillar or spar.',
    source: 'IALA MBS – cardinal marks',
  },
  {
    id: 'Q32',
    q: 'What colour is the light on a cardinal mark?',
    options: ['White', 'Yellow', 'Red', 'Green'],
    why: 'Cardinal marks show white lights, very quick or quick flashing. The number of flashes tells you which quadrant.',
    source: 'IALA MBS – cardinal marks',
  },
  {
    id: 'Q33',
    q: 'Which light does a north cardinal mark show?',
    options: ['Continuous very quick or quick flashing', 'VQ(3) 5s or Q(3) 10s', 'VQ(6)+LFl 10s or Q(6)+LFl 15s', 'VQ(9) 10s or Q(9) 15s'],
    why: 'North: uninterrupted VQ or Q. East: 3 flashes. South: 6 flashes plus a long flash. West: 9 flashes – like a clock face.',
    source: 'IALA MBS – cardinal marks',
  },
  {
    id: 'Q34',
    q: 'You see a north cardinal mark ahead. On which side should you pass it?',
    options: ['On its north side', 'On its south side', 'On either side', 'On its east side'],
    why: 'A cardinal mark is named after the quadrant it is in, seen from the danger. The safe water is on the named side, so you pass north of a north cardinal mark.',
    source: 'IALA MBS – cardinal marks',
  },
  {
    id: 'Q35',
    q: 'The four cardinal quadrants are bounded by which true bearings from the point marked?',
    options: ['NW–NE, NE–SE, SE–SW and SW–NW', 'N–E, E–S, S–W and W–N', '000°–090° and 180°–270° only', 'Any bearings the authority decides'],
    why: 'The quadrants (north, east, south and west) are bounded by the true bearings NW–NE, NE–SE, SE–SW and SW–NW from the point of interest.',
    source: 'IALA MBS – cardinal marks',
  },
  {
    id: 'Q36',
    q: 'What colours is an isolated danger mark?',
    options: ['Black with one or more broad horizontal red bands', 'Red and white vertical stripes', 'Yellow with a black band', 'Red with one broad green band'],
    why: 'An isolated danger mark is black with one or more broad horizontal red bands, with two black spheres as topmark. Its light is white Fl(2).',
    source: 'IALA MBS – isolated danger marks',
  },
  {
    id: 'Q37',
    q: 'What colour is the light on a safe water mark?',
    options: ['White', 'Red', 'Yellow', 'Green'],
    why: 'A safe water mark shows a white light: isophase, occulting, one long flash every 10 s, or Morse "A".',
    source: 'IALA MBS – safe water marks',
  },
  {
    id: 'Q38',
    q: 'What colour is the light on a special mark?',
    options: ['Yellow', 'White', 'Red', 'Blue'],
    why: 'Special marks are yellow and show a yellow light, with a rhythm that cannot be confused with the white lights of cardinal, isolated danger or safe water marks.',
    source: 'IALA MBS – special marks',
  },
  {
    id: 'Q39',
    q: 'What shape is a special mark?',
    options: [
      'Optional, but it must not conflict with lateral or safe water marks',
      'Always a pillar',
      'Always a sphere',
      'Always a spar with a red topmark',
    ],
    why: 'The shape of a special mark is optional, but it must not be confused with a navigational mark. For example, a can-shaped special mark should only be used where it can be passed as a port-hand mark.',
    source: 'IALA MBS – special marks',
  },
  {
    id: 'Q40',
    q: 'You see a mark with a yellow light. Which kind of mark can it NOT be?',
    options: ['A cardinal mark', 'A special mark', 'A data-collection buoy (ODAS)', 'A mark showing a spoil ground or cable area'],
    why: 'Yellow lights are used on special marks, which include ODAS buoys, spoil grounds, cables and pipelines. Cardinal marks always show white lights.',
    source: 'IALA MBS – special marks',
  },
]
