import type { TheoryItem } from '../study/generators/theory'

// Sound and light signal theory (COLREG Part D). The first option is the correct one.
// Added 8 Oct 2026 – waiting for Robin's review.

export const SOUND_THEORY: (TheoryItem & { id: string })[] = [
  {
    id: 'S32b',
    q: 'How long is a "short blast"?',
    options: ['About 1 second', 'About 3 seconds', '4 to 6 seconds', 'Half a second'],
    why: 'Rule 32(b): the word "short blast" means a blast of about one second\'s duration.',
    source: 'Rule 32(b)',
  },
  {
    id: 'S32c',
    q: 'How long is a "prolonged blast"?',
    options: ['From 4 to 6 seconds', 'About 1 second', 'At least 10 seconds', '2 to 3 seconds'],
    why: 'Rule 32(c): the term "prolonged blast" means a blast of from four to six seconds\' duration.',
    source: 'Rule 32(c)',
  },
  {
    id: 'S33a',
    q: 'A vessel of 100 m or more shall be provided with:',
    options: ['A whistle, a bell and a gong', 'A whistle and a bell', 'A whistle only', 'A bell and a gong'],
    why: 'Rule 33(a): a vessel of 12 m or more shall have a whistle, of 20 m or more also a bell, and of 100 m or more also a gong whose tone cannot be confused with that of the bell.',
    source: 'Rule 33(a)',
  },
  {
    id: 'S33b',
    q: 'A vessel of less than 12 m:',
    options: [
      'Need not carry the sound appliances of Rule 33(a), but shall have some other means of making an efficient sound signal',
      'Must carry a whistle and a bell',
      'Never needs to make sound signals',
      'Must carry a gong',
    ],
    why: 'Rule 33(b): a vessel of less than 12 m is not obliged to carry the sound signalling appliances in 33(a), but if she does not, she shall be provided with some other means of making an efficient sound signal.',
    source: 'Rule 33(b)',
  },
  {
    id: 'S34a',
    q: 'When does a power-driven vessel give the manoeuvring signals of Rule 34(a) (for example one short blast)?',
    options: [
      'When vessels are in sight of one another and she is manoeuvring as authorised or required by the Rules',
      'Whenever she alters course, also in fog',
      'Only in narrow channels',
      'Only when the other vessel asks on VHF',
    ],
    why: 'Rule 34(a): when vessels are in sight of one another, a power-driven vessel underway, when manoeuvring as authorised or required by these Rules, shall indicate that manoeuvre by signals on her whistle.',
    source: 'Rule 34(a)',
  },
  {
    id: 'S34b',
    q: 'The light that may supplement the whistle signals of Rule 34(a): what is the minimum interval between successive signals?',
    options: ['10 seconds', '1 second', '2 minutes', '30 seconds'],
    why: 'Rule 34(b): flashes of about one second, the interval between flashes about one second, and the interval between successive signals not less than ten seconds. The light is an all-round white light visible at least 5 miles.',
    source: 'Rule 34(b)',
  },
  {
    id: 'S35a',
    q: 'In restricted visibility, how often shall a power-driven vessel making way sound her fog signal?',
    options: ['At intervals of not more than 2 minutes', 'Every 5 minutes', 'Every 30 seconds', 'Only when she hears another vessel'],
    why: 'Rule 35(a): a power-driven vessel making way through the water shall sound at intervals of not more than 2 minutes one prolonged blast.',
    source: 'Rule 35(a)',
  },
  {
    id: 'S35g',
    q: 'A vessel at anchor in fog wants to warn an approaching vessel. Which signal may she give in addition to the bell?',
    options: ['One short, one prolonged and one short blast', 'Five short blasts', 'One prolonged and two short blasts', 'Three short blasts'],
    why: 'Rule 35(g): a vessel at anchor may in addition sound three blasts in succession, namely one short, one prolonged and one short blast, to give warning of her position and of the possibility of collision.',
    source: 'Rule 35(g)',
  },
  {
    id: 'S35j',
    q: 'In restricted visibility, a vessel of less than 12 m:',
    options: [
      'Need not give the Rule 35 signals, but if she does not, shall make some other efficient sound signal at intervals of not more than 2 minutes',
      'Must give exactly the same signals as a large vessel',
      'Needs to make no sound signals at all',
      'Shall ring a bell every minute',
    ],
    why: 'Rule 35(j): a vessel of less than 12 m is not obliged to give the signals in Rule 35, but if she does not, she shall make some other efficient sound signal at intervals of not more than 2 minutes.',
    source: 'Rule 35(j)',
  },
  {
    id: 'S35k',
    q: 'In restricted visibility, a pilot vessel on duty may add an identity signal of:',
    options: ['Four short blasts', 'Two prolonged blasts', 'One short, one prolonged, one short', 'Five short blasts'],
    why: 'Rule 35(k): a pilot vessel when engaged on pilotage duty may, in addition to the signals in 35(a), (b) or (g), sound an identity signal consisting of four short blasts.',
    source: 'Rule 35(k)',
  },
  {
    id: 'S35e',
    q: 'In fog, the last vessel of a tow (if manned) sounds one prolonged and three short blasts. When?',
    options: [
      'Immediately after the signal made by the towing vessel, if practicable',
      'At the same time as the towing vessel',
      'Only when another vessel is heard',
      'Every minute, independently of the tug',
    ],
    why: 'Rule 35(e): a vessel towed, or if more than one the last vessel of the tow, if manned, shall at intervals of not more than 2 minutes sound four blasts – one prolonged followed by three short – when practicable immediately after the signal made by the towing vessel.',
    source: 'Rule 35(e)',
  },
  // ---- Added 9 Oct 2026 (NEW 9 OCT) – waiting for Robin's review ----
  {
    id: 'S34b2',
    q: 'A vessel in sight gives three flashes on her manoeuvring light. What does it mean?',
    options: ['I am operating astern propulsion', 'I am altering my course to port', 'I am altering my course to starboard', 'I doubt your intentions'],
    why: 'Rule 34(b)(i): one flash – I am altering my course to starboard; two flashes – to port; three flashes – I am operating astern propulsion.',
    source: 'Rule 34(b)',
  },
  {
    id: 'S34d2',
    q: 'The "doubt" signal of at least five short and rapid blasts may be supplemented by a light signal of:',
    options: ['At least five short and rapid flashes', 'One long flash', 'Three flashes', 'A searchlight on the other vessel'],
    why: 'Rule 34(d): the whistle signal may be supplemented by a light signal of at least five short and rapid flashes.',
    source: 'Rule 34(d)',
  },
  {
    id: 'S34e2',
    q: 'You hear one prolonged blast from a vessel approaching a bend. How shall you answer if you are within hearing around the bend?',
    options: ['With one prolonged blast', 'With two short blasts', 'With five short blasts', 'You shall not answer'],
    why: 'Rule 34(e): such signal shall be answered with a prolonged blast by any approaching vessel that may be within hearing around the bend or behind the intervening obstruction.',
    source: 'Rule 34(e)',
  },
  {
    id: 'S34f',
    q: 'A vessel has two whistles more than 100 m apart. How are they used for manoeuvring and warning signals?',
    options: [
      'Only one whistle shall be used',
      'Both whistles shall sound at the same time',
      'The forward whistle for starboard, the after one for port',
      'They shall sound one after the other',
    ],
    why: 'Rule 34(f): if whistles are fitted on a vessel at a distance apart of more than 100 metres, one whistle only shall be used for giving manoeuvring and warning signals.',
    source: 'Rule 34(f)',
  },
  {
    id: 'S35b',
    q: 'In fog, a power-driven vessel underway but stopped sounds two prolonged blasts. What is the interval between the two blasts?',
    options: ['About 2 seconds', 'About 1 second', 'About 5 seconds', 'About 10 seconds'],
    why: 'Rule 35(b): at intervals of not more than 2 minutes, two prolonged blasts in succession with an interval of about 2 seconds between them.',
    source: 'Rule 35(b)',
  },
  {
    id: 'S35c',
    q: 'In restricted visibility, which vessel does NOT sound one prolonged followed by two short blasts?',
    options: ['A power-driven vessel making way', 'A sailing vessel', 'A vessel engaged in fishing', 'A vessel constrained by her draught'],
    why: 'Rule 35(c): a vessel not under command, restricted in her ability to manoeuvre, constrained by her draught, a sailing vessel, a vessel engaged in fishing and a vessel towing or pushing sound one prolonged followed by two short blasts.',
    source: 'Rule 35(c)',
  },
  {
    id: 'S35d',
    q: 'In fog, a vessel engaged in fishing is at anchor. Which signal does she give?',
    options: [
      'One prolonged followed by two short blasts, instead of the anchor bell',
      'The anchor bell only',
      'Two prolonged blasts',
      'Four short blasts',
    ],
    why: 'Rule 35(d): a vessel engaged in fishing, when at anchor, and a vessel restricted in her ability to manoeuvre when carrying out her work at anchor, shall instead of the signals in 35(g) sound the signal in 35(c).',
    source: 'Rule 35(d)',
  },
  {
    id: 'S35f',
    q: 'In fog, a pushing vessel and a vessel pushed ahead, rigidly connected in a composite unit, sound:',
    options: [
      'The signals of a power-driven vessel (one or two prolonged blasts)',
      'One prolonged followed by two short blasts',
      'One prolonged followed by three short blasts',
      'Four short blasts',
    ],
    why: 'Rule 35(f): a pushing vessel and a vessel being pushed ahead, rigidly connected in a composite unit, shall be regarded as a power-driven vessel and give the signals in 35(a) or (b).',
    source: 'Rule 35(f)',
  },
  {
    id: 'S35g2',
    q: 'How does a vessel at anchor in fog ring her bell?',
    options: [
      'Rapidly for about 5 seconds, at intervals of not more than 1 minute',
      'Three strokes every 2 minutes',
      'Continuously',
      'Rapidly for about 1 second every 30 seconds',
    ],
    why: 'Rule 35(g): a vessel at anchor shall at intervals of not more than one minute ring the bell rapidly for about 5 seconds.',
    source: 'Rule 35(g)',
  },
  {
    id: 'S35g3',
    q: 'A vessel of 100 m or more at anchor in fog rings the bell in the fore part. What follows immediately after?',
    options: [
      'The gong, sounded rapidly for about 5 seconds in the after part',
      'One prolonged blast on the whistle',
      'Three strokes on the bell',
      'Nothing – the bell is enough',
    ],
    why: 'Rule 35(g): in a vessel of 100 metres or more the bell shall be sounded in the forepart, and immediately after the ringing of the bell the gong shall be sounded rapidly for about 5 seconds in the after part.',
    source: 'Rule 35(g)',
  },
  {
    id: 'S35h',
    q: 'A vessel aground in fog gives the anchor bell (and gong) signal and, in addition:',
    options: [
      'Three separate and distinct strokes on the bell immediately before and after the rapid ringing',
      'Five short blasts on the whistle',
      'One prolonged blast every minute',
      'Two strokes on the gong',
    ],
    why: 'Rule 35(h): a vessel aground shall give the bell signal and if required the gong signal of 35(g) and shall, in addition, give three separate and distinct strokes on the bell immediately before and after the rapid ringing of the bell.',
    source: 'Rule 35(h)',
  },
  {
    id: 'S35i',
    q: 'A vessel of 12 m or more but less than 20 m at anchor in fog:',
    options: [
      'Need not give the bell signal, but if she does not, shall make some other efficient sound signal at intervals of not more than 2 minutes',
      'Must ring the bell and sound the gong',
      'Needs no sound signal at all',
      'Shall sound one prolonged blast every minute',
    ],
    why: 'Rule 35(i): a vessel of 12 metres or more but less than 20 metres shall not be obliged to give the bell signals in 35(g) and (h). However, if she does not, she shall make some other efficient sound signal at intervals of not more than 2 minutes.',
    source: 'Rule 35(i)',
  },
  {
    id: 'S33c',
    q: 'May the bell or gong be replaced by other equipment?',
    options: [
      'Yes, if it has the same sound characteristics and manual sounding of the signals is always possible',
      'No, never',
      'Yes, by a loudspeaker playing a recording, without any other conditions',
      'Only on vessels of less than 20 m',
    ],
    why: 'Rule 33(a): the bell or gong or both may be replaced by other equipment having the same respective sound characteristics, provided that manual sounding of the prescribed signals shall always be possible.',
    source: 'Rule 33(a)',
  },
  {
    id: 'A3range',
    q: 'What is the minimum range of audibility of the whistle of a vessel of 200 m or more?',
    options: ['2 nautical miles', '1 nautical mile', '0.5 nautical mile', '5 nautical miles'],
    why: 'Annex III 1(c): range of audibility – 200 m or more: 2 miles; 75 m to 200 m: 1.5 miles; 20 m to 75 m: 1 mile; less than 20 m: 0.5 mile.',
    source: 'COLREG Annex III 1(c)',
  },
  {
    id: 'A3freq',
    q: 'How does the whistle of a large vessel differ from that of a small one?',
    options: [
      'A larger vessel has a lower fundamental frequency (deeper tone)',
      'A larger vessel has a higher fundamental frequency',
      'All whistles have the same frequency',
      'Only the length of the blasts differs',
    ],
    why: 'Annex III 1(a): 200 m or more – 70–200 Hz; 75 m to 200 m – 130–350 Hz; less than 75 m – 250–700 Hz. The bigger the ship, the deeper the whistle.',
    source: 'COLREG Annex III 1(a)',
  },
]
